<font color= Magenta>*_Lixandru Andreea-Bianca, grupa 382
<br>
Pepene Adina-Florentina, grupa 382_*

# Exercitii cu functii

<font color= blue>Ex1:</font> Sa se scrie o functie care primeste ca parametru o lista de numere si returneaza un tuplu continand: suma
elementelor si diferenta maxima dintre elementele listei.

In [1]:
from typing import List, Tuple

from itertools import combinations

import numpy as np

In [2]:
def sum_dif(my_list: List[float])-> Tuple[float, float]:
    ''' Aceasta functie determina suma elementelor si diferenta maxima dintre elementele listei
    Parametri:
    my_list= lista de numere de tip float
    Tip returnat: Tuple[float, float]'''
    
    sum_list = sum(my_list)
    first_elem_diff, second_elem_diff = max(combinations(my_list, 2), key = lambda sub: abs(sub[0]-sub[1])) 
  
    return sum_list, abs(first_elem_diff - second_elem_diff)

In [3]:
my_list: np.array = [0.2, 5.3, 4.2, 3.2, 5., 10.]

print (sum_dif(my_list))

(27.9, 9.8)


<font color= blue>Ex2:</font> Scrieti o functie care preia doua liste si returneaza True daca cele doua liste de numere contin cel putin k
elemente comune (k>= 1 dat ca parametru intreg, valoare implicita 1), False altfel.

In [4]:
def k_commun_elem(first_list: List[float], second_list: List[float], k: int = 1)-> bool:
    '''Aceasta functie verifica daca doua liste au cel putin k elemente comune.
    Parametri:
    first_lis, second_list= liste cu numere reale
    k= nr minim de elemente comune necesare; setat implicit 1
    Tip returnat: bool; True daca exista cel putin k elemnte comune si False, altfel.'''
    
    return len(set(first_list).intersection(second_list)) >= k 

In [5]:
first_list = [2., 9., 8., 7.]
second_list = [2., 9., 18., 17.]

print (k_commun_elem(first_list,second_list,3))

False


<font color= blue>Ex3:</font> Sa se scrie o functie care determina daca o lista contine cuvinte reprezentand doar numere intregi (optional:
numere fractionare, scrise sub forma parte intreaga, optional urmata de punct zecimal, optional urmata de
parte fractionara: 1, 2., 13.14) (Puteti folosi modulul re pentru lucrul cu expresii regulate.) Functia trebuie
sa testeze daca:
A. elementele din lista sunt stringuri
B. fiecare din stringuri este un numar

In [6]:
import re

In [7]:
def is_string(my_list: List)-> bool:
    '''Aceasta functie verifica daca tipul de date al input-ului este string.
    Parametri: 
    my_list= lista pentru care verificam tipul de date
    Tip returnat: bool; True daca tipul de date este string si False, altfel.'''
    
    string_type = [True if type(elem)== str else False for elem in my_list]
    return all(my_list)

In [8]:
def is_number(my_list: List)-> bool:
    '''Aceasta functie verifica daca string-urile primite sunt numere intregi.
    Parametri: 
    my_list= o lista de string-uri
    Tip returnat: bool; returneaza True daca fiecare string reprezinta un numar intreg si False, altfel.'''
    
    other_list = [re.match("^[-+]?([0]|[1-9][0-9]*)$", item) is not None for item in my_list]
    
    return all(other_list)

In [9]:
my_list = ["0", "-1234", "1234", "10"]
if is_string(my_list):
    print (is_number(my_list))
else:
    print("Lista nu contine doar siruri de caractere! Mai incearca o data!")

True


<font color= blue>Ex4:</font> Sa se scrie o functie care returneaza numarul de vocale si de consoane dintr-un parametru dat - rezultatul
returnat de functie este tuplu cu doua valori. Cuvantul se va converti la litere mici in interiorul functiei.

In [10]:
def vowels_and_consonants(word: str)-> Tuple[int, int]:
    '''Aceasta functie contorizeaza cate vocale si cate consoane sunt intr-un cuvant.
    Parametri: 
    word= cuvantul pt care vrem sa facem contorizarea 
    Tip returnat: Tuple[int, int], unde prima valoare reprezinta numarul de vocale din 
    cuvant si al doilea reprezinta numarul de consoane din cuvant'''
    
    vowels=['a','e','i','o','u']
    number_of_vowels=0
    number_of_consonants=0
    copy_word=word.lower()
    print(copy_word)
    
    for i in copy_word:
        if i in vowels:
            number_of_vowels += 1
        else:
            number_of_consonants += 1
            
    return number_of_vowels, number_of_consonants

In [11]:
word ="ABRAcadABRA"
print (word)
print (vowels_and_consonants(word))

ABRAcadABRA
abracadabra
(5, 6)


<font color= blue>Ex5:</font> Sa se scrie o functie care primind o lista de dictionare, returneaza True daca toate dictionarele contin cel
putin n elemente, n transmis ca parametru, False altfel.

In [12]:
def number_of_elements(dictionary_list: list, n:int)-> bool:
    '''Aceasta functie verifica daca toate dictionarele contin n elemente.
    Parametri: 
    dictionary_list= lista de dictionare
    n= nr minim de elemente necesare
    Tip returnat: bool; returneaza True daca toate dictionarele contin n elemente si False, altfel.'''
    
    for d in dictionary_list:
        if len(d) < n:
            return False
        
    return True

In [13]:
dictionary_list = [{'a':'1','b':'2'},{'d':'4','e':'5','f':'6'},{'g':'7','h':'8','i':'9','j':'10'}]
print (dictionary_list)
print (number_of_elements(dictionary_list,2))

[{'a': '1', 'b': '2'}, {'d': '4', 'e': '5', 'f': '6'}, {'g': '7', 'h': '8', 'i': '9', 'j': '10'}]
True


<font color= blue>Ex6: </font> Sa se scrie o functie recursiva care sa faca ridicarea la putere a unui numar, astfel:

$a^{n}$={
            a , daca n=1  SAU 
            $(a^{n//2})^{2}$ , daca n este par  SAU 
            $(a^{n//2})^{2}*a$ , daca n este impar, n>1
        }

unde prin n//2 se reprezinta catul impartirii intregi intre si 2.

In [14]:
def function(a: int, n: int) -> int:
    '''Aceasta functie calculeaza recursiv ridicarea la putere a unui numar.
    Parametri: 
    a= exponentul 
    n= puterea 
    Tip returnat: int, valoarea numarul a la puterea n.'''
    
    if n == 1:
        return a
    if n%2 == 0:
        return function(a, n//2)**2
    return function(a, n//2)**2 * a

In [15]:
number=2
print(function(number,10))

1024


# Exercitii simple folosind NumPy

<font color= blue>Ex1:</font> (0.5 puncte) Pentru un vector NumPy dat, sa se determine care sunt elementele unice, in ordine
descrescatoare. Exemplu: pentru x = np.array([-4, 3, 5, 3, 2, 1, -3, -4, 2, -4]) functia
scrisa de dvs va intoarce rezultatul [ 5, 3, 2, 1, -3, -4] .

In [17]:
def function(vector: np.array)-> np.array:
    '''Aceasta functie returneaza elementele unice in ordine descrescatoare dintr-un array.
    Parametri: 
    vector= un np.array care contine elementele 
    Tip returnat: np.array, care contine elementele unice in ordine descrescatoare din vector'''
    
    return np.unique(np.sort(vector))[:: -1]

In [18]:
vector: np.array = np.array([-4, 3, 5, 3, 2, 1, -3, -4, 2, -4])
print (vector)
print (function(vector))

[-4  3  5  3  2  1 -3 -4  2 -4]
[ 5  3  2  1 -3 -4]


<font color= blue>Ex2:</font> (0.5 puncte) Pentru un vector NumPy dat, sa se determine care e elementul cel mai frecvent si cel mai putin
frecvent (tuplu de 2 valori). Daca exista mai multe numere cele mai frecvente (cele mai putin frecvente), se
va raporta oricare din ele. Exemplu: pentru x = np.array([-4, 3, 5, 3, 2, 1, -3, -4, 2, -4])
functia scrisa de dvs va intoarce rezultatul (-4, -3) .

In [19]:
from collections import Counter 

def function_2(vector: np.array)-> Tuple[int, int]: 
    '''Aceasta functie determina cel mai frecvent si cel mai putin frecvent element dintr-un vector.
    Parametri:
    vector= un np.array ce ontine elementele
    Tip returnat: un tuplu de int, int, unde prima valoare reprezinta cel mai frecvent element,
    iar a doua valoare reprezinta ce mai putin frecvent element din vector'''
    
    occurence_count: int = Counter(vector) 
    return occurence_count.most_common()[0][0],occurence_count.most_common()[-1][0]

In [20]:
vector: np.array = np.array([-4, 3, 5, 3, 2, 1, -3, -4, 2, -4]) 
print(function_2(vector))

(-4, -3)


<font color= blue>Ex3:</font> (0.5 puncte) Plecand de la o matrice, sa se scrie o functie care returneaza vectorul minimelor de pe linii si
vectorul maximelor de pe coloane. Exemplu: pentru matricea mat = np.array([[1, 2, 3, 4], [1, -2,
3, -4], [3, 10, 3, 4]]) functia va returna tuplul de vectori: (array([ 1, -4, 3]), array([ 3,
10, 3, 4])) . Indicatie: folositi-va de parametrul axis .

In [21]:
def function_3(mat: np.array)-> Tuple[np.array, np.array]:
    '''Aceasta functie determina vectorul minimelor de pe linii si vectorul maximelor de pe coloane dintr-o matrice.
    Parametri: 
    mat=  este un np.array ce contine elementele 
    Tip returnat: un tuplu de np.array, np.array, unde primul element reprezinta vectorul minimelor de pe linii,
    iar al doilea element reprezinta vectorul maximelor de pe coloane'''
    
    return np.min(mat,axis=1),np.max(mat,axis=0)

In [22]:
mat: np.array = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]]) 
print(mat)
print(function_3(mat))

[[ 1  2  3  4]
 [ 1 -2  3 -4]
 [ 3 10  3  4]]
(array([ 1, -4,  3]), array([ 3, 10,  3,  4]))


<font color= blue>Ex4:</font> (0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii sau de pe coloane,
in functie de valoarea unui parametru boolean compute_on_lines . Exemplu: pentru matricea mat =
np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]]) si parametrul
compute_on_lines=True , functia va returna vectorul [ 24 24 360] , iar pentru
compute_on_lines=False se va returna [ 3 -40 27 -64] .

In [2]:
def function_4(mat: np.array, compute_on_lines: bool)-> np.array:
    '''Aceasta functie calculeaza produsul elementelor pe linii sau pe coloane.
    Parametri:
    mat= un np.array care contine elementele matricii
    compute_on_lines= o valoare booleana; True daca se face calculul produsului pe linii si
    False daca se face calculul produsului pe coloane'''
    
    return np.prod(mat, axis = int(compute_on_lines))

In [3]:
mat: np.array= np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]]) 
print(function_4(mat, True))

[ 24  24 360]


<font color= blue>Ex5:</font> (0.5 puncte) Determinati daca macar unul din elementele unei matrice a este mai mare decat cel de pe
pozitie corespondenta din b (adica daca avem macar o pereche de indecsi (i, j) pentru care a[i, j] > b[i, j]).
Daca da, se va returna o astfel de pereche de indecsi; daca nu, se va returna None.

In [19]:
def function_5(a: np.array,b: np.array)-> Tuple[int, int] or None:
    '''Aceasta functie verifica daca macar unul din elementele matricii a este mai mare decat
    cel de pe pozitia corespondenta din tabloul b.
    Parametri:
    a, b= matrici de tipul np.array care contin elementele tablourilor 
    Tip returnat: un tuplu de tip int, int, care semnifica perechea i si j
    unde se indeplineste proprietatea a>b'''
    
    i, j = np.where((a>b)== True)
    
    if i.size != 0:
        return (i[0],j[0])
    else:
        return None

In [21]:
mat:np.array = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 6, 4]]) 
mat2:np.array = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 5, 4]]) 

print("Line and column:", function_5(mat, mat2))

Line and column: (2, 2)


<font color= blue>Ex6:</font> (0.5 puncte) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui
interval [min, max] dat prin parametri.

In [27]:
def function_6 (mat: np.array, a: int, b: int)-> Tuple [np.array, np.array]:
    '''Aceasta functie determina pozitiile pe care se afla elementele
    din afara unui interval dat.
    Parametri: 
    mat= un np.array ce contine elementele matricii
    a= capatul inferior al intervalului
    b= capatul superior al intervalului
    Tipul returnat: un tiplu de tip [np.array, np.array], unde
    primul array contine indicii liniilor si al doilea array contine indicii coloanelor
    elementelor care indeplinesc conditia'''
    
    return np.where(mat<a) or np.where(mat>b)

In [28]:
from itertools import product
mat:np.array = np.array([[1, 2, 3, 4], [-1, -2, -3, -4], [5, 6, 7, 8]]) 
print(mat)
i, j= function_6(mat, 5, 8)
print("Positions:", list (zip(i, j)))

[[ 1  2  3  4]
 [-1 -2 -3 -4]
 [ 5  6  7  8]]
Positions: [(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3)]


<font color= blue>Ex7:</font> (1 punct) Se considera vectorul: a = np.array([230, 10, 284, 39, 76]) . Folosind indexarea logica,
sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate).
Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se
afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.

In [29]:
def function_7(a: np.array)-> np.array:
    '''Aceasta functie multiplica valorile care sunt mai mici de 100 pana cand
    ajung mai mari de 100 si returneaza elementele care sunt cuprinse intre 150 si 200.
    Parametri: 
    a= un np.array care contine elementele matricii
    Tipul returnat: un np.array ce contine elementele care dupa multiplicare
    sunt cuprinse intre 150 si 200'''
    
    while np.any(a<100):
        a[a<100]*= 2
        
    return a[np.logical_and(a>= 150, a<= 200)]

In [30]:
a:np.array = np.array([230, 10, 284, 39, 76])

print (function_7(a))

[160 156 152]


<font color= blue>Ex8:</font> (1 punct) Sa se scrie o functie pair_max care preia doi vectori de aceeasi lungime si returneaza maximele
pe pozitiile corespunzatoare: python
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
#iesire dorita:
array([ 4, 7, 9, 100, 300, 230, 3]) . Functia va verifica cu assert ca vectorii au lungimi
egale.

In [31]:
def pair_max(a: np.array, b: np.array)-> np.array:
    '''Aceasta functie determina maximele dintre doi vectori de aceeasi lungime.
    Parametri:
    a, b= np.array care sunt niste vectori ce contin elementele
    Tipul returnat: np.array, care contine maximele'''
    
    return np.maximum(a,b)

In [32]:
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1]) 

print(pair_max(a,b))

[  4   7   9 100 300 230   3]


<font color= blue>Ex9:</font> (1 punct) Descarcati setul de date Iris de la adresa 'https://archive.ics.uci.edu/ml/machine-learningdatabases/
iris/iris.data (https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data)', si incarcati-l
intr--o matrice NumPy, folosind np.genfromtxt . Alegeti aleator 10 pozitii in matricea de 150 linii si 4
coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primind la
intrare o matrice, returneaza un tuplu cu indicii de linii respectiv de coloane in care se gasesc valori NaN.

In [33]:
mat: np.array = np.genfromtxt('iris.data', delimiter = ',')

mat= mat[:, :-1]

print(mat)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [34]:
def get_nan_positions(mat: np.array)-> Tuple[int, int]:
    '''Aceasta functie pune pe 10 pozitii random din matrice valoarea nan.
    Parametri:
    mat= un np.array cu elemente
    Tipul returnat: un tuplu de tip int, int, unde primul element reprezinta 
    pozitiile liniilor si al doilea element reprezinta pozitiile coloanelor'''
    
    rows: np.array = np.random.randint(mat.shape[0], size = 10)
    cols: np.array = np.random.randint(mat.shape[1], size = 10)
    
    mat[rows, cols] = np.nan

    return rows, cols

In [39]:
vec = np.array([[1., 2., 3.], [4., 5., 6.], [8., 9., 10.],
                [11., 12., 13.], [4., 5., 6.], [8., 9., 10.],
                [4., 5., 6.], [8., 9., 10.]])

#print(get_nan_positions(vec))
i, j = get_nan_positions(mat)
print("Pos:", list(zip(i,j)))

Pos: [(7, 3), (45, 1), (53, 3), (103, 2), (67, 2), (24, 1), (38, 0), (119, 2), (99, 3), (123, 3)]


<font color= blue>Ex10:</font> (1 punct) Sa se construiasca o functie care returneaza cele mai mici k valori dintr-un vector de cel putin k
elemente, impreuna cu pozitiile lor.

In [36]:
def function_10(vector: np.array, k: int)-> Tuple [np.array, np.array]:
    '''Aceasta functie returneaza cele mai mici k valori dintr-un vector impreuna cu pozitiile lor.
    Parametri:
    vector= un np.array cu elemente
    k= un int care este conditia
    Tipul returnat: un tuplu de tip np.array, np.array, unde 
    primul array contine cele mai mici 'k' valori din vector
    si al doilea array contine pozitiile lor in vector'''
    
    assert len(vector)>=k,"The array must have at least 'K' elements!"
    return np.sort(vector)[:k], np.argsort(vector)[:k]

In [37]:
vector = np.array([3, 7, 9, 13, -10, 200, 2, -1, 0, -11])
i, j = function_10(vector, 7)
print("Number:",i,"and indices:",j)

Number: [-11 -10  -1   0   2   3   7] and indices: [9 4 7 8 6 0 1]
