<font color = Magenta> _Lixandru Andreea-Bianca 382
 <br>   Pepene Adina-Florentina 382_

# Laborator 6

Versiunea 2020-04-01

## Modele de clasificare

Folositi 4 seturi de date pentru probleme de clasificare, plecand de la repository-urile specificate in Cursul 5; de exemplu, [ics.uci.edu](http://archive.ics.uci.edu/ml/datasets.php?format=mat&task=cla&att=&area=&numAtt=&numIns=&type=mvar&sort=nameUp&view=table). Cel putin doua seturi de date sa fie cu valori lipsa. 


1. (20 puncte) Aplicati o metoda de missing value imputation, unde este cazul; justificati si documentati metoda folosita.
1. (numar de modele * numar de seturi de date \* 1 punct = 20 de puncte) Pentru fiecare set de date aplicati 5 modele de clasificare din scikit learn. Pentru fiecare raportati: acuratete, scorul F1 - a se vedea [sklearn.metrics](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) - folosind 5 fold cross validation. Raportati mediile rezultatelor atat pentru fold-urile de antrenare, cat si pentru cele de testare. Rularile se vor face cu valori fixate ale hiperparametrilor. 
1. (numar modele * 4 puncte = 20 puncte) Documentati in jupyter notebook fiecare din modelele folosite, in limba romana. Daca acelasi algoritm e folosit pentru mai multe seturi de date, puteti face o sectiune separata cu documentarea algoritmilor + trimitere la algoritm. 
1. (numar de modele * numar de seturi de date \* 1 punct = 20 de puncte) Pentru fiecare model: efectuati o cautare a hiperparametrilor optimi folosind grid search si random search (cu parametrul cv = 4), folosind 5 fold cross validation. 

Se acorda 20 de puncte din oficiu. 

Exemple de modele de clasificare:
1. [Multi-layer Perceptron classifier](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier)
1. [KNN](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier)
1. [SVM](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC)
1. [Gaussian processes](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html#sklearn.gaussian_process.GaussianProcessClassifier)
1. [RBF](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.RBF.html#sklearn.gaussian_process.kernels.RBF)
1. [Decision tree](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier)
1. [Random forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier)
1. [Gaussian Naive bayes](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB) 

*Predare:* 
1. Fiecare student va depune pe site-ul de elearning fisier Jupyter notebook sau arhiva cu astfel de fisiere; 
1. In fiecare fisier se specifica numele celor doi studenti care au lucra in echipa. 
1. Predarea se face in saptamana 13-17 aprilie 2020
1. Revedeti formele ulterioare ale acestui document pentru precizari despre: continutul rezultatelor raportate, modalitate de notare.

# <font color= Magenta> Rezolvare

Citim seturile de date si ne uitam care dintre ele au valori lipsa.

In [1]:
import pandas as pd 
import numpy as np

In [2]:
names_yeast = ["mcg", "gvh","alm","mit","erl","pox","vac","nuc","class"]

df_yeast = pd.read_csv('./data/yeast/yeast.data',sep=r" +", engine="python", names=names_yeast)

df_yeast.head()

mcg   gvh   alm   mit  erl  pox   vac   nuc class
ADT1_YEAST  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22   MIT
ADT2_YEAST  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22   MIT
ADT3_YEAST  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22   MIT
AAR2_YEAST  0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22   NUC
AATM_YEAST  0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22   MIT

In [3]:
df_yeast.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1484 entries, ADT1_YEAST to G6PD_YEAST
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   mcg     1484 non-null   float64
 1   gvh     1484 non-null   float64
 2   alm     1484 non-null   float64
 3   mit     1484 non-null   float64
 4   erl     1484 non-null   float64
 5   pox     1484 non-null   float64
 6   vac     1484 non-null   float64
 7   nuc     1484 non-null   float64
 8   class   1484 non-null   object 
dtypes: float64(8), object(1)
memory usage: 115.9+ KB


In [4]:
df_wine = pd.read_csv('./data/wine/winequality-red.csv', sep=';')

df_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [6]:
names_breast_cancer = ["class","age","menopause","tumor-size","inv-nodes","node-caps","deg-malig",
                       "breast","breast-quad","irradiat"]

df_breast_cancer = pd.read_csv('./data/breast_cancer/breast-cancer.data', names=names_breast_cancer)

df_breast_cancer['class'] = df_breast_cancer['class'].map({'recurrence-events': 1, 'no-recurrence-events': 0})

df_breast_cancer['age'] = df_breast_cancer['age'].map({'10-19': 1, '20-29': 2, '30-39': 3,
                                                       '40-49': 4, '50-59': 5, '60-69': 6,
                                                       '70-79': 7, '80-89': 8, '90-99': 9})

df_breast_cancer['menopause'] = df_breast_cancer['menopause'].map({'premeno' : 1,'lt40' : 2, 'ge40' : 3})

df_breast_cancer['tumor-size'] = df_breast_cancer['tumor-size'].map({'0-4': 0, '5-9': 5, '10-14': 10, '15-19': 15, 
                                                                   '20-24': 20, '25-29': 25, '30-34': 30, '35-39': 35, 
                                                                   '40-44': 40, '45-49': 45, '50-54': 50, '55-59': 55})

df_breast_cancer['inv-nodes'] = df_breast_cancer['inv-nodes'].map({'0-2':0, '3-5':3, '6-8':6, '9-11':9, '12-14':12, 
                                                                   '15-17':15,'18-20':18, '21-23':21, '24-26':24, 
                                                                   '27-29':27, '30-32':30, '33-35':33, '36-39':36})

df_breast_cancer['node-caps'] = df_breast_cancer['node-caps'].map({'no': 0, 'yes': 1})

df_breast_cancer['breast'] = df_breast_cancer['breast'].map({'left': 0, 'right': 1})

df_breast_cancer['breast-quad'] = df_breast_cancer['breast-quad'].map({'left_up': 1, 'left_low': 2, 'right_up': 3,
                                                                       'right_low': 4, 'central': 5})

df_breast_cancer['irradiat'] = df_breast_cancer['irradiat'].map({'no': 0, 'yes': 1})

df_breast_cancer.head()

class  age  menopause  tumor-size  inv-nodes  node-caps  deg-malig  breast  \
0      0    3          1          30          0        0.0          3       0   
1      0    4          1          20          0        0.0          2       1   
2      0    4          1          20          0        0.0          2       0   
3      0    6          3          15          0        0.0          2       1   
4      0    4          1           0          0        0.0          2       1   

   breast-quad  irradiat  
0          2.0         0  
1          3.0         0  
2          2.0         0  
3          1.0         0  
4          4.0         0

In [7]:
'''In data set-ul breast_cancer missing values sunt marcate prin '?',
nu prin valori NaN, asa ca dorim sa inlocuim  valorile '?' cu valori
NaN astfel incat sa putem vedea cre sunt valorile necompletate si
sa le putem inlocui sau sterge.'''

df_breast_cancer = df_breast_cancer.replace('?', np.nan)
df_breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   class        286 non-null    int64  
 1   age          286 non-null    int64  
 2   menopause    286 non-null    int64  
 3   tumor-size   286 non-null    int64  
 4   inv-nodes    286 non-null    int64  
 5   node-caps    278 non-null    float64
 6   deg-malig    286 non-null    int64  
 7   breast       286 non-null    int64  
 8   breast-quad  285 non-null    float64
 9   irradiat     286 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 22.5 KB


In [8]:
names_primary_tumor =["class","age","sex","histologic-type","degree-of-diffe","bone","bone-marrow","lung",
                     "pleura","peritoneum","liver","brain","skin","neck","supraclavicular","axillar","mediastinum","abdomnial"]

df_primary_tumor = pd.read_csv("./data/primary_tumor/primary-tumor.data", names=names_primary_tumor)

df_primary_tumor.head()

class  age sex histologic-type degree-of-diffe  bone  bone-marrow  lung  \
0      1    1   1               ?               3     2            2     1   
1      1    1   1               ?               3     2            2     2   
2      1    1   2               2               3     1            2     2   
3      1    1   2               ?               3     1            2     1   
4      1    1   2               ?               3     1            2     1   

   pleura  peritoneum  liver  brain skin  neck  supraclavicular axillar  \
0       2           2      2      2    2     2                2       2   
1       2           2      1      2    2     2                1       2   
2       2           2      2      2    2     2                2       2   
3       1           2      2      2    2     2                2       2   
4       1           2      2      2    2     2                2       2   

   mediastinum  abdomnial  
0            2          2  
1            1          2  
2            1          2  
3            1          2  
4            1          2

In [9]:
df_primary_tumor = df_primary_tumor.replace('?', np.nan)

df_primary_tumor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   class            339 non-null    int64 
 1   age              339 non-null    int64 
 2   sex              338 non-null    object
 3   histologic-type  272 non-null    object
 4   degree-of-diffe  184 non-null    object
 5   bone             339 non-null    int64 
 6   bone-marrow      339 non-null    int64 
 7   lung             339 non-null    int64 
 8   pleura           339 non-null    int64 
 9   peritoneum       339 non-null    int64 
 10  liver            339 non-null    int64 
 11  brain            339 non-null    int64 
 12  skin             338 non-null    object
 13  neck             339 non-null    int64 
 14  supraclavicular  339 non-null    int64 
 15  axillar          338 non-null    object
 16  mediastinum      339 non-null    int64 
 17  abdomnial        339 non-null    in

<font color=blue>Ex1:</font> Aplicati o metoda de missing value imputation, unde este cazul; justificati si documentati metoda folosita.
<br>
><br>Metode posibile:
<br>1. Eliminarea liniilor care contin valori nan.
<br>2. Eliminarea coloanelor care contin nan.
<br>3. Umplerea valorilor nan cu:
> -> o valoare constanta
><br>-> copierea ultimei valori cunoscute(ffill)
><br>-> umplere 'inapoi'(bfill)
><br>-> o valoare calculata (ex: media)

In [10]:
'''Pentru dataset-ul breast_cancer am ales sa umplem valorile nan
prin copierea ultimei valori cunoscute, intrucat am dori sa pastram
cat mai multe din liniile si coloanele data set-ului nostru.
Pe coloanele care lipsesc valori nu exista o varietate mare de valori,
deci putem folosi ultima valoare cunoscuta. Setul de date este aproape
complet si nu necesita multe adaugari.'''

df_breast_cancer = df_breast_cancer.fillna(method='ffill')

df_breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   class        286 non-null    int64  
 1   age          286 non-null    int64  
 2   menopause    286 non-null    int64  
 3   tumor-size   286 non-null    int64  
 4   inv-nodes    286 non-null    int64  
 5   node-caps    286 non-null    float64
 6   deg-malig    286 non-null    int64  
 7   breast       286 non-null    int64  
 8   breast-quad  286 non-null    float64
 9   irradiat     286 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 22.5 KB


In [11]:
'''Pentru dataset-ul primary_tumor am ales sa umplem valorile lipsa
cu media de pe coloana, intrucat am observat ca lipsesc multe valori 
de pe aceeasi coloana, deci nu putem avea o evidenta clara asupra
datelor anterioare. Totusi, nu putem decide inca daca renuntam
la coloana digree-of-diffe. Ramane de vazut...'''

df_primary_tumor = df_primary_tumor.apply(lambda x: pd.to_numeric(x), axis=0)

df_primary_tumor = df_primary_tumor.fillna(round(df_primary_tumor.mean()))

df_primary_tumor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   class            339 non-null    int64  
 1   age              339 non-null    int64  
 2   sex              339 non-null    float64
 3   histologic-type  339 non-null    float64
 4   degree-of-diffe  339 non-null    float64
 5   bone             339 non-null    int64  
 6   bone-marrow      339 non-null    int64  
 7   lung             339 non-null    int64  
 8   pleura           339 non-null    int64  
 9   peritoneum       339 non-null    int64  
 10  liver            339 non-null    int64  
 11  brain            339 non-null    int64  
 12  skin             339 non-null    float64
 13  neck             339 non-null    int64  
 14  supraclavicular  339 non-null    int64  
 15  axillar          339 non-null    float64
 16  mediastinum      339 non-null    int64  
 17  abdomnial       

<font color=blue>Ex2:</font> Pentru fiecare set de date aplicati 5 modele de clasificare din scikit learn. Pentru fiecare raportati: acuratete, scorul F1 - a se vedea sklearn.metrics - folosind 5 fold cross validation. Raportati mediile rezultatelor atat pentru fold-urile de antrenare, cat si pentru cele de testare. Rularile se vor face cu valori fixate ale hiperparametrilor.

Trebuie sa separam datele in date de intrare si date de iesire.

In [12]:
x_yeast = df_yeast[["mcg", "gvh", "alm", "mit", "erl", "pox", "vac","nuc"]].to_numpy()
y_yeast = df_yeast["class"].to_numpy()

print("X_yeast", x_yeast[:20, :])
print("Y_yeast", y_yeast[:20])

X_yeast [[0.58 0.61 0.47 0.13 0.5  0.   0.48 0.22]
 [0.43 0.67 0.48 0.27 0.5  0.   0.53 0.22]
 [0.64 0.62 0.49 0.15 0.5  0.   0.53 0.22]
 [0.58 0.44 0.57 0.13 0.5  0.   0.54 0.22]
 [0.42 0.44 0.48 0.54 0.5  0.   0.48 0.22]
 [0.51 0.4  0.56 0.17 0.5  0.5  0.49 0.22]
 [0.5  0.54 0.48 0.65 0.5  0.   0.53 0.22]
 [0.48 0.45 0.59 0.2  0.5  0.   0.58 0.34]
 [0.55 0.5  0.66 0.36 0.5  0.   0.49 0.22]
 [0.4  0.39 0.6  0.15 0.5  0.   0.58 0.3 ]
 [0.43 0.39 0.54 0.21 0.5  0.   0.53 0.27]
 [0.42 0.37 0.59 0.2  0.5  0.   0.52 0.29]
 [0.4  0.42 0.57 0.35 0.5  0.   0.53 0.25]
 [0.6  0.4  0.52 0.46 0.5  0.   0.53 0.22]
 [0.66 0.55 0.45 0.19 0.5  0.   0.46 0.22]
 [0.46 0.44 0.52 0.11 0.5  0.   0.5  0.22]
 [0.47 0.39 0.5  0.11 0.5  0.   0.49 0.4 ]
 [0.58 0.47 0.54 0.11 0.5  0.   0.51 0.26]
 [0.5  0.34 0.55 0.21 0.5  0.   0.49 0.22]
 [0.61 0.6  0.55 0.21 0.5  0.   0.5  0.25]]
Y_yeast ['MIT' 'MIT' 'MIT' 'NUC' 'MIT' 'CYT' 'MIT' 'NUC' 'MIT' 'CYT' 'NUC' 'NUC'
 'CYT' 'MIT' 'MIT' 'CYT' 'CYT' 'NUC' 'NUC' 'NUC']


In [13]:
x_wine = df_wine [["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", 
                   "free sulfur dioxide", "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]].to_numpy()
y_wine = df_wine["quality"].to_numpy()

print("X_wine", x_wine[:20, :])
print("Y_wine", y_wine[:20])

X_wine [[7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00]
 [7.800e+00 7.600e-01 4.000e-02 2.300e+00 9.200e-02 1.500e+01 5.400e+01
  9.970e-01 3.260e+00 6.500e-01 9.800e+00]
 [1.120e+01 2.800e-01 5.600e-01 1.900e+00 7.500e-02 1.700e+01 6.000e+01
  9.980e-01 3.160e+00 5.800e-01 9.800e+00]
 [7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.400e+00 6.600e-01 0.000e+00 1.800e+00 7.500e-02 1.300e+01 4.000e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00]
 [7.300e+00 6.500e-01 0.000e+00 1.200e+00 6.500e-02 1.500e+01 2.100e+01
  9.946e-01 3.390e+00 4.700e-01 1.000e+01]
 [7.800e+00 5.800e-01 2.000e-02 2.000e+00 7.300e-02 9.000e+00 1.800e+01
 

In [14]:
x_breast_cancer = df_breast_cancer[["age", "menopause", "tumor-size", "inv-nodes", "node-caps", "deg-malig", "breast", 
                                    "breast-quad", "irradiat"]].to_numpy()
y_breast_cancer = df_breast_cancer["class"].to_numpy()

print("X_breast_cancer", x_breast_cancer[:20, :])
print("Y_breast_cancer", y_breast_cancer[:20])

X_breast_cancer [[ 3.  1. 30.  0.  0.  3.  0.  2.  0.]
 [ 4.  1. 20.  0.  0.  2.  1.  3.  0.]
 [ 4.  1. 20.  0.  0.  2.  0.  2.  0.]
 [ 6.  3. 15.  0.  0.  2.  1.  1.  0.]
 [ 4.  1.  0.  0.  0.  2.  1.  4.  0.]
 [ 6.  3. 15.  0.  0.  2.  0.  2.  0.]
 [ 5.  1. 25.  0.  0.  2.  0.  2.  0.]
 [ 6.  3. 20.  0.  0.  1.  0.  2.  0.]
 [ 4.  1. 50.  0.  0.  2.  0.  2.  0.]
 [ 4.  1. 20.  0.  0.  2.  1.  1.  0.]
 [ 4.  1.  0.  0.  0.  3.  0.  5.  0.]
 [ 5.  3. 25.  0.  0.  2.  0.  2.  0.]
 [ 6.  2. 10.  0.  0.  1.  0.  3.  0.]
 [ 5.  3. 25.  0.  0.  3.  0.  3.  0.]
 [ 4.  1. 30.  0.  0.  3.  0.  1.  0.]
 [ 6.  2. 30.  0.  0.  1.  0.  2.  0.]
 [ 4.  1. 15.  0.  0.  2.  0.  2.  0.]
 [ 5.  1. 30.  0.  0.  3.  0.  2.  0.]
 [ 6.  3. 30.  0.  0.  3.  0.  2.  0.]
 [ 5.  3. 30.  0.  0.  1.  1.  3.  0.]]
Y_breast_cancer [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [15]:
x_primary_tumor = df_primary_tumor[["age", "sex", "histologic-type", "degree-of-diffe", "bone", "bone-marrow", "lung",
                     "pleura", "peritoneum", "liver", "brain", "skin", "neck", "supraclavicular", "axillar", 
                    "mediastinum", "abdomnial"]].to_numpy()
y_primary_tumor = df_primary_tumor["class"].to_numpy()

print("X_primary_tumor", x_primary_tumor[:20, :])
print("Y_primary_tumor", y_primary_tumor[:20])

X_primary_tumor [[1. 1. 2. 3. 2. 2. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 2. 3. 2. 2. 2. 2. 2. 1. 2. 2. 2. 1. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 2. 2. 2. 2. 1. 2. 2. 1. 1. 1. 2.]
 [2. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 1. 1. 1. 2. 2. 2.]
 [2. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2. 2. 2. 2.]
 [2. 1. 1. 2. 1. 2. 2. 2. 2. 2. 2. 2. 1. 1. 2. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 1. 2. 2. 2. 2. 2. 1. 2. 1. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 1. 2. 2. 1. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 3. 2. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 1. 2.]
 [2. 1. 1. 2. 2. 2. 2. 1. 2. 1. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2. 1. 2.]
 [2. 1. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 1. 1. 2. 1. 2.]
 [2. 1. 2. 3

Separam setul de date in set de antrenare si set de testare.
<br> Cand folosim random state facem un random mai stabil.

In [16]:
from sklearn.model_selection import train_test_split
from collections import Counter

In [17]:
def check_balanced_data_set(y_train, y_test) -> None:
    print(Counter(y_train))
    print(Counter(y_test))

<font color= magenta> Yeast dataset.

In [18]:
X_train_yeast, X_test_yeast, y_train_yeast, y_test_yeast = train_test_split(x_yeast,
                                                                            y_yeast, 
                                                                            test_size=1/3,
                                                                            shuffle=True,
                                                                            random_state=10)

print(y_train_yeast[:20])
print(y_test_yeast[:20])

['CYT' 'NUC' 'NUC' 'NUC' 'CYT' 'EXC' 'ERL' 'EXC' 'ME3' 'EXC' 'CYT' 'CYT'
 'CYT' 'ME3' 'CYT' 'MIT' 'ME2' 'ME3' 'NUC' 'NUC']
['CYT' 'CYT' 'NUC' 'CYT' 'NUC' 'CYT' 'NUC' 'CYT' 'MIT' 'ME3' 'CYT' 'MIT'
 'ME3' 'EXC' 'ME3' 'CYT' 'ME3' 'NUC' 'ME2' 'CYT']


<font color= magenta> Wine dataset.

In [19]:
X_train_wine, X_test_wine, y_train_wine, y_test_wine = train_test_split(x_wine,
                                                                        y_wine, 
                                                                        test_size=1/3,
                                                                        shuffle=True,
                                                                        random_state=10)

print(y_train_wine[:20])
print(y_test_wine[:20])

[6 5 6 6 5 6 5 6 5 5 7 4 7 6 6 6 6 6 6 7]
[5 5 6 6 5 6 7 6 5 5 7 4 5 5 6 5 6 6 6 5]


<font color= magenta> Breast cancer dataset.

In [20]:
X_train_breast_cancer, X_test_breast_cancer, y_train_breast_cancer, y_test_breast_cancer = train_test_split(x_breast_cancer,
                                                                                                            y_breast_cancer, 
                                                                                                            test_size=1/3,
                                                                                                            shuffle=True,
                                                                                                            random_state=10)

print(y_train_breast_cancer[:20])
print(y_test_breast_cancer[:20])

[0 0 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0]
[0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0]


<font color= magenta> Primary tumor dataset.

In [21]:
X_train_primary_tumor, X_test_primary_tumor, y_train_primary_tumor, y_test_primary_tumor = train_test_split(x_primary_tumor,
                                                                                                            y_primary_tumor, 
                                                                                                            test_size=1/3,
                                                                                                            shuffle=True,
                                                                                                            random_state=10)

print(y_train_primary_tumor[:20])
print(y_test_primary_tumor[:20])

[ 1 19 22  3 12  5  1 18  1  1 22  3  1 11  2  5  1  8  1  1]
[17  1 22 18 11 11 11 14 11  7 11  7 11 22  2 18 11  5  1  1]


In [22]:
check_balanced_data_set(y_train_yeast, y_test_yeast)

Counter({'CYT': 308, 'NUC': 285, 'MIT': 163, 'ME3': 111, 'ME2': 36, 'ME1': 27, 'EXC': 25, 'VAC': 18, 'POX': 12, 'ERL': 4})
Counter({'CYT': 155, 'NUC': 144, 'MIT': 81, 'ME3': 52, 'ME1': 17, 'ME2': 15, 'VAC': 12, 'EXC': 10, 'POX': 8, 'ERL': 1})


In [23]:
check_balanced_data_set(y_train_wine, y_test_wine)

Counter({5: 446, 6: 436, 7: 136, 4: 33, 3: 8, 8: 7})
Counter({5: 235, 6: 202, 7: 63, 4: 20, 8: 11, 3: 2})


In [24]:
check_balanced_data_set(y_train_breast_cancer, y_test_breast_cancer)

Counter({0: 137, 1: 53})
Counter({0: 64, 1: 32})


In [25]:
check_balanced_data_set(y_train_primary_tumor, y_test_primary_tumor)

Counter({1: 58, 5: 29, 18: 21, 22: 16, 14: 16, 2: 14, 11: 13, 4: 9, 12: 8, 17: 7, 7: 7, 3: 6, 8: 6, 13: 6, 19: 3, 20: 2, 15: 2, 10: 1, 21: 1, 6: 1})
Counter({1: 26, 11: 15, 5: 10, 22: 8, 18: 8, 14: 8, 12: 8, 7: 7, 2: 6, 4: 5, 17: 3, 19: 3, 3: 3, 16: 1, 10: 1, 13: 1})


# <font color=magenta> 1. KNeighbourClassifier

In [26]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.model_selection import cross_val_score

In [27]:
def k_neighbours_method(X_train, y_train, X_test, y_test, number_of_neighbors) -> None:
    model = KNeighborsClassifier(n_neighbors=number_of_neighbors)
    model.fit(X_train, y_train)
    
    y_predicated_train = model.predict(X_train)
    y_predicated_test = model.predict(X_test)
    
    print ("Train score:", model.score(X_train, y_train)*100)
    print ("Test score:", model.score(X_test, y_test)*100)
    print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
    print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
    print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
    # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
    print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
    print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
    print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)

In [28]:
k_neighbours_method(X_train_yeast, y_train_yeast, X_test_yeast, y_test_yeast, 59)

Train score: 57.93731041456016
Test score: 57.97979797979798
Different outputs train: 416 from total of 989
Different outputs test: 208 from total of 495
Accuracy train: 57.93731041456016
F1-score train: 57.93731041456016
Accuracy test: 57.97979797979798
F1-score test: 57.97979797979798


In [29]:
k_neighbours_method(X_train_wine, y_train_wine, X_test_wine, y_test_wine, 59)

Train score: 53.47091932457786
Test score: 49.906191369606
Different outputs train: 496 from total of 1066
Different outputs test: 267 from total of 533
Accuracy train: 53.47091932457786
F1-score train: 53.47091932457786
Accuracy test: 49.906191369606
F1-score test: 49.906191369606


In [30]:
k_neighbours_method(X_train_breast_cancer, y_train_breast_cancer, X_test_breast_cancer, y_test_breast_cancer, 20)

Train score: 74.21052631578947
Test score: 65.625
Different outputs train: 49 from total of 190
Different outputs test: 33 from total of 96
Accuracy train: 74.21052631578947
F1-score train: 74.21052631578947
Accuracy test: 65.625
F1-score test: 65.625


In [31]:
k_neighbours_method(X_train_primary_tumor, y_train_primary_tumor, X_test_primary_tumor, y_test_primary_tumor, 59)

Train score: 42.0353982300885
Test score: 34.51327433628318
Different outputs train: 131 from total of 226
Different outputs test: 74 from total of 113
Accuracy train: 42.0353982300885
F1-score train: 42.0353982300885
Accuracy test: 34.51327433628318
F1-score test: 34.51327433628318


# <font color=Magenta> 2. MLPClassifier

In [32]:
from sklearn.neural_network import MLPClassifier

In [33]:
def mlp_method(X_train, y_train, X_test, y_test) -> None:
    #‘sgd’ refers to stochastic gradient descent.
    model =  MLPClassifier()
    model.fit(X_train, y_train)
    
    y_predicated_train = model.predict(X_train)
    y_predicated_test = model.predict(X_test)
    
    print ("Train score:", model.score(X_train, y_train)*100)
    print ("Test score:", model.score(X_test, y_test)*100)
    print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
    print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
    print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
    # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
    print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
    print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
    print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)

In [34]:
mlp_method(X_train_yeast, y_train_yeast, X_test_yeast, y_test_yeast)

Train score: 58.54398382204246
Test score: 61.212121212121204
Different outputs train: 410 from total of 989
Different outputs test: 192 from total of 495
Accuracy train: 58.54398382204246
F1-score train: 58.54398382204246
Accuracy test: 61.212121212121204
F1-score test: 61.212121212121204


D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [35]:
mlp_method(X_train_wine, y_train_wine, X_test_wine, y_test_wine)

Train score: 62.28893058161351
Test score: 51.594746716697934
Different outputs train: 402 from total of 1066
Different outputs test: 258 from total of 533
Accuracy train: 62.28893058161351
F1-score train: 62.28893058161351
Accuracy test: 51.594746716697934
F1-score test: 51.594746716697934


D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [36]:
mlp_method(X_train_breast_cancer, y_train_breast_cancer, X_test_breast_cancer, y_test_breast_cancer)

Train score: 78.42105263157895
Test score: 71.875
Different outputs train: 41 from total of 190
Different outputs test: 27 from total of 96
Accuracy train: 78.42105263157895
F1-score train: 78.42105263157895
Accuracy test: 71.875
F1-score test: 71.875


D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [37]:
mlp_method(X_train_primary_tumor, y_train_primary_tumor, X_test_primary_tumor, y_test_primary_tumor)

Train score: 50.0
Test score: 39.823008849557525
Different outputs train: 113 from total of 226
Different outputs test: 68 from total of 113
Accuracy train: 50.0
F1-score train: 50.0
Accuracy test: 39.823008849557525
F1-score test: 39.823008849557525


D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


# <font color=Magenta> 3. SVC

In [38]:
from sklearn.svm import SVC

In [39]:
def svc_method(X_train, y_train, X_test, y_test) -> None:
    model = SVC(class_weight=None)
    model.fit(X_train,y_train)
    
    y_predicated_train = model.predict(X_train)
    y_predicated_test = model.predict(X_test)
    
    print ("Train score:", model.score(X_train, y_train)*100)
    print ("Test score:", model.score(X_test, y_test)*100)
    print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
    print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
    print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
    # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
    print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
    print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
    print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)

In [40]:
svc_method(X_train_yeast, y_train_yeast, X_test_yeast, y_test_yeast)

Train score: 61.27401415571284
Test score: 60.80808080808081
Different outputs train: 383 from total of 989
Different outputs test: 194 from total of 495
Accuracy train: 61.27401415571284
F1-score train: 61.27401415571284
Accuracy test: 60.80808080808081
F1-score test: 60.80808080808081


In [41]:
svc_method(X_train_wine, y_train_wine, X_test_wine, y_test_wine)

Train score: 52.15759849906192
Test score: 46.52908067542214
Different outputs train: 510 from total of 1066
Different outputs test: 285 from total of 533
Accuracy train: 52.15759849906192
F1-score train: 52.15759849906192
Accuracy test: 46.52908067542214
F1-score test: 46.52908067542214


In [42]:
svc_method(X_train_breast_cancer, y_train_breast_cancer, X_test_breast_cancer, y_test_breast_cancer)

Train score: 72.63157894736842
Test score: 68.75
Different outputs train: 52 from total of 190
Different outputs test: 30 from total of 96
Accuracy train: 72.63157894736842
F1-score train: 72.63157894736842
Accuracy test: 68.75
F1-score test: 68.75


In [43]:
svc_method(X_train_primary_tumor, y_train_primary_tumor, X_test_primary_tumor, y_test_primary_tumor)

Train score: 62.83185840707964
Test score: 37.16814159292036
Different outputs train: 84 from total of 226
Different outputs test: 71 from total of 113
Accuracy train: 62.83185840707964
F1-score train: 62.83185840707964
Accuracy test: 37.16814159292036
F1-score test: 37.168141592920364


# <font color = magenta> 4. GaussianProcessClassifier

In [44]:
from sklearn.gaussian_process import GaussianProcessClassifier

In [45]:
def gaussian_method(X_train, y_train, X_test, y_test) -> None:
    model = GaussianProcessClassifier()
    model.fit(X_train, y_train)
    
    y_predicated_train = model.predict(X_train)
    y_predicated_test = model.predict(X_test)
    
    print ("Train score:", model.score(X_train, y_train)*100)
    print ("Test score:", model.score(X_test, y_test)*100)
    print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
    print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
    print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
    # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
    print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
    print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
    print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)

In [46]:
gaussian_method(X_train_yeast, y_train_yeast, X_test_yeast, y_test_yeast)

Train score: 53.791708796764404
Test score: 54.94949494949495
Different outputs train: 457 from total of 989
Different outputs test: 223 from total of 495
Accuracy train: 53.791708796764404
F1-score train: 53.791708796764404
Accuracy test: 54.94949494949495
F1-score test: 54.94949494949495


In [47]:
gaussian_method(X_train_wine, y_train_wine, X_test_wine, y_test_wine)

Train score: 97.46716697936209
Test score: 55.34709193245778
Different outputs train: 27 from total of 1066
Different outputs test: 238 from total of 533
Accuracy train: 97.46716697936209
F1-score train: 97.46716697936209
Accuracy test: 55.34709193245778
F1-score test: 55.34709193245778


In [48]:
gaussian_method(X_train_breast_cancer, y_train_breast_cancer, X_test_breast_cancer, y_test_breast_cancer)

Train score: 96.3157894736842
Test score: 62.5
Different outputs train: 7 from total of 190
Different outputs test: 36 from total of 96
Accuracy train: 96.3157894736842
F1-score train: 96.3157894736842
Accuracy test: 62.5
F1-score test: 62.5


In [49]:
gaussian_method(X_train_primary_tumor, y_train_primary_tumor, X_test_primary_tumor, y_test_primary_tumor)

Train score: 73.45132743362832
Test score: 46.902654867256636
Different outputs train: 60 from total of 226
Different outputs test: 60 from total of 113
Accuracy train: 73.45132743362832
F1-score train: 73.45132743362832
Accuracy test: 46.902654867256636
F1-score test: 46.902654867256636


# <font color=magenta> 5. GaussianNB

In [50]:
from sklearn.naive_bayes import GaussianNB

In [51]:
def gaussian_nb_method(X_train, y_train, X_test, y_test) -> None:
    model = GaussianNB()
    model.fit(X_train, y_train)
      
    y_predicated_train = model.predict(X_train)
    y_predicated_test = model.predict(X_test)
    
    print ("Train score:", model.score(X_train, y_train)*100)
    print ("Test score:", model.score(X_test, y_test)*100)
    print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
    print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
    print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
    # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
    print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
    print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
    print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)

In [52]:
gaussian_nb_method(X_train_yeast, y_train_yeast, X_test_yeast, y_test_yeast)

Train score: 12.335692618806876
Test score: 13.535353535353536
Different outputs train: 867 from total of 989
Different outputs test: 428 from total of 495
Accuracy train: 12.335692618806876
F1-score train: 12.335692618806876
Accuracy test: 13.535353535353536
F1-score test: 13.535353535353536


In [53]:
gaussian_nb_method(X_train_wine, y_train_wine, X_test_wine, y_test_wine)

Train score: 57.5984990619137
Test score: 48.405253283302066
Different outputs train: 452 from total of 1066
Different outputs test: 275 from total of 533
Accuracy train: 57.5984990619137
F1-score train: 57.5984990619137
Accuracy test: 48.405253283302066
F1-score test: 48.405253283302066


In [54]:
gaussian_nb_method(X_train_breast_cancer, y_train_breast_cancer, X_test_breast_cancer, y_test_breast_cancer)

Train score: 74.21052631578947
Test score: 70.83333333333334
Different outputs train: 49 from total of 190
Different outputs test: 28 from total of 96
Accuracy train: 74.21052631578947
F1-score train: 74.21052631578947
Accuracy test: 70.83333333333334
F1-score test: 70.83333333333334


In [55]:
gaussian_nb_method(X_train_primary_tumor, y_train_primary_tumor, X_test_primary_tumor, y_test_primary_tumor)

Train score: 24.336283185840706
Test score: 15.04424778761062
Different outputs train: 171 from total of 226
Different outputs test: 96 from total of 113
Accuracy train: 24.336283185840706
F1-score train: 24.336283185840706
Accuracy test: 15.04424778761062
F1-score test: 15.04424778761062


# <font color= magenta> 6. DecisionTreeClassifier

In [56]:
from sklearn.tree import DecisionTreeClassifier

In [277]:
def decision_tree_method(X_train, y_train, X_test, y_test) -> None:
    model = DecisionTreeClassifier(max_depth=5, min_samples_leaf=15)
    model.fit(X_train, y_train)
       
    y_predicated_train = model.predict(X_train)
    y_predicated_test = model.predict(X_test)
    
    print ("Train score:", model.score(X_train, y_train)*100)
    print ("Test score:", model.score(X_test, y_test)*100)
    print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
    print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
    print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
    # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
    print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
    print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
    print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)

In [278]:
decision_tree_method(X_train_yeast, y_train_yeast, X_test_yeast, y_test_yeast)
#aici avem sigur overfit

Train score: 61.57735085945399
Test score: 57.97979797979798
Different outputs train: 380 from total of 989
Different outputs test: 208 from total of 495
Accuracy train: 61.57735085945399
F1-score train: 61.57735085945399
Accuracy test: 57.97979797979798
F1-score test: 57.97979797979798


In [279]:
decision_tree_method(X_train_wine, y_train_wine, X_test_wine, y_test_wine)

Train score: 66.60412757973734
Test score: 56.09756097560976
Different outputs train: 356 from total of 1066
Different outputs test: 234 from total of 533
Accuracy train: 66.60412757973734
F1-score train: 66.60412757973734
Accuracy test: 56.09756097560976
F1-score test: 56.09756097560976


In [280]:
decision_tree_method(X_train_breast_cancer, y_train_breast_cancer, X_test_breast_cancer, y_test_breast_cancer)

Train score: 77.36842105263158
Test score: 72.91666666666666
Different outputs train: 43 from total of 190
Different outputs test: 26 from total of 96
Accuracy train: 77.36842105263158
F1-score train: 77.36842105263158
Accuracy test: 72.91666666666666
F1-score test: 72.91666666666666


In [281]:
decision_tree_method(X_train_primary_tumor, y_train_primary_tumor, X_test_primary_tumor, y_test_primary_tumor)

Train score: 42.47787610619469
Test score: 33.6283185840708
Different outputs train: 130 from total of 226
Different outputs test: 75 from total of 113
Accuracy train: 42.47787610619469
F1-score train: 42.47787610619469
Accuracy test: 33.6283185840708
F1-score test: 33.6283185840708


# <font color= magenta> 7. RandomForestClassifier

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [237]:
def random_forest_method(X_train, y_train, X_test, y_test, max_depth, min_samples_leaf) -> None:
    model = RandomForestClassifier(max_depth=max_depth, min_samples_leaf=min_samples_leaf)
    model.fit(X_train, y_train)
       
    y_predicated_train = model.predict(X_train)
    y_predicated_test = model.predict(X_test)
    
    print ("Train score:", model.score(X_train, y_train)*100)
    print ("Test score:", model.score(X_test, y_test)*100)
    print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
    print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
    print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
    # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
    print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
    print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
    print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)

In [238]:
random_forest_method(X_train_yeast, y_train_yeast, X_test_yeast, y_test_yeast, 4, 6)

Train score: 62.689585439838226
Test score: 60.80808080808081
Different outputs train: 369 from total of 989
Different outputs test: 194 from total of 495
Accuracy train: 62.689585439838226
F1-score train: 62.689585439838226
Accuracy test: 60.80808080808081
F1-score test: 60.80808080808081


In [239]:
random_forest_method(X_train_wine, y_train_wine, X_test_wine, y_test_wine, 3, 6)

Train score: 63.60225140712945
Test score: 59.66228893058161
Different outputs train: 388 from total of 1066
Different outputs test: 215 from total of 533
Accuracy train: 63.60225140712945
F1-score train: 63.60225140712945
Accuracy test: 59.66228893058161
F1-score test: 59.66228893058161


In [240]:
random_forest_method(X_train_breast_cancer, y_train_breast_cancer, X_test_breast_cancer, y_test_breast_cancer, 5, 15)

Train score: 76.84210526315789
Test score: 71.875
Different outputs train: 44 from total of 190
Different outputs test: 27 from total of 96
Accuracy train: 76.84210526315789
F1-score train: 76.84210526315788
Accuracy test: 71.875
F1-score test: 71.875


In [241]:
random_forest_method(X_train_primary_tumor, y_train_primary_tumor, X_test_primary_tumor, y_test_primary_tumor, 5, 6)

Train score: 51.32743362831859
Test score: 39.823008849557525
Different outputs train: 110 from total of 226
Different outputs test: 68 from total of 113
Accuracy train: 51.32743362831859
F1-score train: 51.32743362831859
Accuracy test: 39.823008849557525
F1-score test: 39.823008849557525


Yeast 55
<br>Wine Red ?
<br>Breast Cancer 75
<br>Primary tumor 48

# GaussianNB

<br>
<br>
<br>Acest tip de clasificare este foarte simplu, de aceea pentru seturile noastre de date obtinem un rezultat bun pentru setul de date breast_cancer, intrucat acesta se imparte in doua clase(no-recurrence-events si recurrence-events).
<br>Pentru celelalte seturi de date rezultatul este evident, intrucat celelalte seturi de date au in jur de 10 clase.


#  Decision Tree Classifier

<br>
<br>
<br>Aceasta metoda poate clasifica atat doua clase cat si mai multe clase intr-un dataset.
<br>
<br>Parametri:
<br>splitter-> reprezinta strategia aleasa pentru divizarea nodurilor
<br>max_depth-> reprezinta adancimea arborelui
<br>min_samples_split-> nr minim de sample-uri necesare 
<br>min_samples_leaf-> nr minim de sample-uri necesare ca un nod sa fie frunza

# Random Forest Classifier
<br>
<br>
<br>Aceasta metoda foloseste o padure de arbori de decizie random.
<br>Are ca scop controlul fenomenului de overfitting.
<br>
<br>Parametri:
<br>n_estimators-> nr de arbori din padure
<br>max_depth-> adancimea arborelui 
<br>min_samples_split-> nr de sample-uri necesare unui nod pentru a se face split
<br>min_samples_leaf-> nr minim de sample-uri necesare ca un nod sa fie frunza
<br>si altele

<br>
<br>
<br>Observatii:
<br>n_estimators-> nu produce overfitting daca crestem nr de arbori 
<br>max_features-> cu cat e mai mic cu atat evitam overfitting-ul, dar daca e prea mic reteaua face undefitting
<br>max_depth-> are un rol important, reduce complexitatea