<font color = Magenta> _Lixandru Andreea-Bianca 382
 <br>   Pepene Adina-Florentina 382_

# Laborator 6

Versiunea 2020-04-01

## Modele de clasificare

Folositi 4 seturi de date pentru probleme de clasificare, plecand de la repository-urile specificate in Cursul 5; de exemplu, [ics.uci.edu](http://archive.ics.uci.edu/ml/datasets.php?format=mat&task=cla&att=&area=&numAtt=&numIns=&type=mvar&sort=nameUp&view=table). Cel putin doua seturi de date sa fie cu valori lipsa. 


1. (20 puncte) Aplicati o metoda de missing value imputation, unde este cazul; justificati si documentati metoda folosita.
1. (numar de modele * numar de seturi de date \* 1 punct = 20 de puncte) Pentru fiecare set de date aplicati 5 modele de clasificare din scikit learn. Pentru fiecare raportati: acuratete, scorul F1 - a se vedea [sklearn.metrics](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) - folosind 5 fold cross validation. Raportati mediile rezultatelor atat pentru fold-urile de antrenare, cat si pentru cele de testare. Rularile se vor face cu valori fixate ale hiperparametrilor. 
1. (numar modele * 4 puncte = 20 puncte) Documentati in jupyter notebook fiecare din modelele folosite, in limba romana. Daca acelasi algoritm e folosit pentru mai multe seturi de date, puteti face o sectiune separata cu documentarea algoritmilor + trimitere la algoritm. 
1. (numar de modele * numar de seturi de date \* 1 punct = 20 de puncte) Pentru fiecare model: efectuati o cautare a hiperparametrilor optimi folosind grid search si random search (cu parametrul cv = 4), folosind 5 fold cross validation. 

Se acorda 20 de puncte din oficiu. 

Exemple de modele de clasificare:
1. [Multi-layer Perceptron classifier](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier)
1. [KNN](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier)
1. [SVM](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC)
1. [Gaussian processes](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html#sklearn.gaussian_process.GaussianProcessClassifier)
1. [RBF](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.RBF.html#sklearn.gaussian_process.kernels.RBF)
1. [Decision tree](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier)
1. [Random forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier)
1. [Gaussian Naive bayes](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB) 

*Predare:* 
1. Fiecare student va depune pe site-ul de elearning fisier Jupyter notebook sau arhiva cu astfel de fisiere; 
1. In fiecare fisier se specifica numele celor doi studenti care au lucra in echipa. 
1. Predarea se face in saptamana 13-17 aprilie 2020
1. Revedeti formele ulterioare ale acestui document pentru precizari despre: continutul rezultatelor raportate, modalitate de notare.

# <font color= Magenta> Rezolvare

Citim seturile de date si ne uitam care dintre ele au valori lipsa.

In [1]:
import pandas as pd 
import numpy as np

In [2]:
names_yeast = ["name", "mcg", "gvh","alm","mit","erl","pox","vac","nuc"]

df_yeast = pd.read_csv('./data/yeast/yeast.data',sep=r" +", engine="python", names=names_yeast)

df_yeast.head()

name   mcg   gvh   alm  mit  erl   pox   vac  nuc
ADT1_YEAST  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22  MIT
ADT2_YEAST  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22  MIT
ADT3_YEAST  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22  MIT
AAR2_YEAST  0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22  NUC
AATM_YEAST  0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22  MIT

In [3]:
df_yeast.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1484 entries, ADT1_YEAST to G6PD_YEAST
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    1484 non-null   float64
 1   mcg     1484 non-null   float64
 2   gvh     1484 non-null   float64
 3   alm     1484 non-null   float64
 4   mit     1484 non-null   float64
 5   erl     1484 non-null   float64
 6   pox     1484 non-null   float64
 7   vac     1484 non-null   float64
 8   nuc     1484 non-null   object 
dtypes: float64(8), object(1)
memory usage: 115.9+ KB


In [4]:
df_wine = pd.read_csv('./data/wine/winequality-red.csv', sep=';')

df_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [6]:
names_breast_cancer = ["class","age","menopause","tumor-size","inv-nodes","node-caps","deg-malig",
                       "breast","breast-quad","irradiat"]

df_breast_cancer = pd.read_csv('./data/breast_cancer/breast-cancer.data', names=names_breast_cancer)

df_breast_cancer.head()

class    age menopause tumor-size inv-nodes node-caps  \
0  no-recurrence-events  30-39   premeno      30-34       0-2        no   
1  no-recurrence-events  40-49   premeno      20-24       0-2        no   
2  no-recurrence-events  40-49   premeno      20-24       0-2        no   
3  no-recurrence-events  60-69      ge40      15-19       0-2        no   
4  no-recurrence-events  40-49   premeno        0-4       0-2        no   

   deg-malig breast breast-quad irradiat  
0          3   left    left_low       no  
1          2  right    right_up       no  
2          2   left    left_low       no  
3          2  right     left_up       no  
4          2  right   right_low       no

In [7]:
'''In data set-ul breast_cancer missing values sunt marcate prin '?',
nu prin valori NaN, asa ca dorim sa inlocuim  valorile '?' cu valori
NaN astfel incat sa putem vedea cre sunt valorile necompletate si
sa le putem inlocui sau sterge.'''

df_breast_cancer = df_breast_cancer.replace('?', np.nan)
df_breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   class        286 non-null    object
 1   age          286 non-null    object
 2   menopause    286 non-null    object
 3   tumor-size   286 non-null    object
 4   inv-nodes    286 non-null    object
 5   node-caps    278 non-null    object
 6   deg-malig    286 non-null    int64 
 7   breast       286 non-null    object
 8   breast-quad  285 non-null    object
 9   irradiat     286 non-null    object
dtypes: int64(1), object(9)
memory usage: 22.5+ KB


In [8]:
names_primary_tumor =["class","age","sex","histologic-type","degree-of-diffe","bone","bone-marrow","lung",
                     "pleura","peritoneum","liver","brain","skin","neck","supraclavicular","axillar","mediastinum","abdomnial"]

df_primary_tumor = pd.read_csv("./data/primary_tumor/primary-tumor.data", names=names_primary_tumor)

df_primary_tumor.head()

class  age sex histologic-type degree-of-diffe  bone  bone-marrow  lung  \
0      1    1   1               ?               3     2            2     1   
1      1    1   1               ?               3     2            2     2   
2      1    1   2               2               3     1            2     2   
3      1    1   2               ?               3     1            2     1   
4      1    1   2               ?               3     1            2     1   

   pleura  peritoneum  liver  brain skin  neck  supraclavicular axillar  \
0       2           2      2      2    2     2                2       2   
1       2           2      1      2    2     2                1       2   
2       2           2      2      2    2     2                2       2   
3       1           2      2      2    2     2                2       2   
4       1           2      2      2    2     2                2       2   

   mediastinum  abdomnial  
0            2          2  
1            1          2  
2            1          2  
3            1          2  
4            1          2

In [9]:
df_primary_tumor = df_primary_tumor.replace('?', np.nan)

df_primary_tumor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   class            339 non-null    int64 
 1   age              339 non-null    int64 
 2   sex              338 non-null    object
 3   histologic-type  272 non-null    object
 4   degree-of-diffe  184 non-null    object
 5   bone             339 non-null    int64 
 6   bone-marrow      339 non-null    int64 
 7   lung             339 non-null    int64 
 8   pleura           339 non-null    int64 
 9   peritoneum       339 non-null    int64 
 10  liver            339 non-null    int64 
 11  brain            339 non-null    int64 
 12  skin             338 non-null    object
 13  neck             339 non-null    int64 
 14  supraclavicular  339 non-null    int64 
 15  axillar          338 non-null    object
 16  mediastinum      339 non-null    int64 
 17  abdomnial        339 non-null    in

<font color=blue>Ex1:</font> Aplicati o metoda de missing value imputation, unde este cazul; justificati si documentati metoda folosita.
<br>
<br>Metode posibile:
<br>1. Eliminarea liniilor care contin valori nan.
<br>2. Eliminarea coloanelor care contin nan.
<br>3. Umplerea valorilor nan cu:
<br>-> o valoare constanta
<br>-> copierea ultimei valori cunoscute(ffill)
<br>-> umplere 'inapoi'(bfill)
<br>-> o valoare calculata (ex: media)

In [10]:
'''Pentru dataset-ul breast_cancer am ales sa umplem valorile nan
prin copierea ultimei valori cunoscute, intrucat am dori sa pastram
cat mai multe din liniile si coloanele data set-ului nostru.
Pe coloanele care lipsesc valori nu exista o varietate mare de valori,
deci putem folosi ultima valoare cunoscuta. Setul de date este aproape
complet si nu necesita multe adaugari.'''

df_breast_cancer = df_breast_cancer.fillna(method='ffill')

df_breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   class        286 non-null    object
 1   age          286 non-null    object
 2   menopause    286 non-null    object
 3   tumor-size   286 non-null    object
 4   inv-nodes    286 non-null    object
 5   node-caps    286 non-null    object
 6   deg-malig    286 non-null    int64 
 7   breast       286 non-null    object
 8   breast-quad  286 non-null    object
 9   irradiat     286 non-null    object
dtypes: int64(1), object(9)
memory usage: 22.5+ KB


In [11]:
'''Pentru dataset-ul primary_tumor am ales sa umplem valorile lipsa
cu media de pe coloana, intrucat am observat ca lipsesc multe valori 
de pe aceeasi coloana, deci nu putem avea o evidenta clara asupra
datelor anterioare. Totusi, nu putem decide inca daca renuntam
la coloana digree-of-diffe. Ramane de vazut...'''

df_primary_tumor = df_primary_tumor.apply(lambda x: pd.to_numeric(x), axis=0)

df_primary_tumor = df_primary_tumor.fillna(round(df_primary_tumor.mean()))

df_primary_tumor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   class            339 non-null    int64  
 1   age              339 non-null    int64  
 2   sex              339 non-null    float64
 3   histologic-type  339 non-null    float64
 4   degree-of-diffe  339 non-null    float64
 5   bone             339 non-null    int64  
 6   bone-marrow      339 non-null    int64  
 7   lung             339 non-null    int64  
 8   pleura           339 non-null    int64  
 9   peritoneum       339 non-null    int64  
 10  liver            339 non-null    int64  
 11  brain            339 non-null    int64  
 12  skin             339 non-null    float64
 13  neck             339 non-null    int64  
 14  supraclavicular  339 non-null    int64  
 15  axillar          339 non-null    float64
 16  mediastinum      339 non-null    int64  
 17  abdomnial       

<font color=blue>Ex2:</font> Pentru fiecare set de date aplicati 5 modele de clasificare din scikit learn. Pentru fiecare raportati: acuratete, scorul F1 - a se vedea sklearn.metrics - folosind 5 fold cross validation. Raportati mediile rezultatelor atat pentru fold-urile de antrenare, cat si pentru cele de testare. Rularile se vor face cu valori fixate ale hiperparametrilor.

Trebuie sa separam datele in date de intrare si date de iesire.

In [12]:
x_yeast = df_yeast[["name", "mcg", "gvh", "alm", "mit", "erl", "pox", "vac"]].to_numpy()
y_yeast = df_yeast["nuc"].to_numpy()

print("X_yeast", x_yeast[:20, :])
print("Y_yeast", y_yeast[:20])

X_yeast [[0.58 0.61 0.47 0.13 0.5  0.   0.48 0.22]
 [0.43 0.67 0.48 0.27 0.5  0.   0.53 0.22]
 [0.64 0.62 0.49 0.15 0.5  0.   0.53 0.22]
 [0.58 0.44 0.57 0.13 0.5  0.   0.54 0.22]
 [0.42 0.44 0.48 0.54 0.5  0.   0.48 0.22]
 [0.51 0.4  0.56 0.17 0.5  0.5  0.49 0.22]
 [0.5  0.54 0.48 0.65 0.5  0.   0.53 0.22]
 [0.48 0.45 0.59 0.2  0.5  0.   0.58 0.34]
 [0.55 0.5  0.66 0.36 0.5  0.   0.49 0.22]
 [0.4  0.39 0.6  0.15 0.5  0.   0.58 0.3 ]
 [0.43 0.39 0.54 0.21 0.5  0.   0.53 0.27]
 [0.42 0.37 0.59 0.2  0.5  0.   0.52 0.29]
 [0.4  0.42 0.57 0.35 0.5  0.   0.53 0.25]
 [0.6  0.4  0.52 0.46 0.5  0.   0.53 0.22]
 [0.66 0.55 0.45 0.19 0.5  0.   0.46 0.22]
 [0.46 0.44 0.52 0.11 0.5  0.   0.5  0.22]
 [0.47 0.39 0.5  0.11 0.5  0.   0.49 0.4 ]
 [0.58 0.47 0.54 0.11 0.5  0.   0.51 0.26]
 [0.5  0.34 0.55 0.21 0.5  0.   0.49 0.22]
 [0.61 0.6  0.55 0.21 0.5  0.   0.5  0.25]]
Y_yeast ['MIT' 'MIT' 'MIT' 'NUC' 'MIT' 'CYT' 'MIT' 'NUC' 'MIT' 'CYT' 'NUC' 'NUC'
 'CYT' 'MIT' 'MIT' 'CYT' 'CYT' 'NUC' 'NUC' 'NUC']


In [13]:
x_wine = df_wine [["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", 
                   "free sulfur dioxide", "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]].to_numpy()
y_wine = df_wine["quality"].to_numpy()

print("X_wine", x_wine[:20, :])
print("Y_wine", y_wine[:20])

X_wine [[7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00]
 [7.800e+00 7.600e-01 4.000e-02 2.300e+00 9.200e-02 1.500e+01 5.400e+01
  9.970e-01 3.260e+00 6.500e-01 9.800e+00]
 [1.120e+01 2.800e-01 5.600e-01 1.900e+00 7.500e-02 1.700e+01 6.000e+01
  9.980e-01 3.160e+00 5.800e-01 9.800e+00]
 [7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.400e+00 6.600e-01 0.000e+00 1.800e+00 7.500e-02 1.300e+01 4.000e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00]
 [7.300e+00 6.500e-01 0.000e+00 1.200e+00 6.500e-02 1.500e+01 2.100e+01
  9.946e-01 3.390e+00 4.700e-01 1.000e+01]
 [7.800e+00 5.800e-01 2.000e-02 2.000e+00 7.300e-02 9.000e+00 1.800e+01
 

In [14]:
x_breast_cancer = df_breast_cancer[["age", "menopause", "tumor-size", "inv-nodes", "node-caps", "deg-malig", "breast", 
                                    "breast-quad", "irradiat"]].to_numpy()
y_breast_cancer = df_breast_cancer["class"].to_numpy()

print("X_breast_cancer", x_breast_cancer[:20, :])
print("Y_breast_cancer", y_breast_cancer[:20])

X_breast_cancer [['30-39' 'premeno' '30-34' '0-2' 'no' 3 'left' 'left_low' 'no']
 ['40-49' 'premeno' '20-24' '0-2' 'no' 2 'right' 'right_up' 'no']
 ['40-49' 'premeno' '20-24' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['60-69' 'ge40' '15-19' '0-2' 'no' 2 'right' 'left_up' 'no']
 ['40-49' 'premeno' '0-4' '0-2' 'no' 2 'right' 'right_low' 'no']
 ['60-69' 'ge40' '15-19' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['50-59' 'premeno' '25-29' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['60-69' 'ge40' '20-24' '0-2' 'no' 1 'left' 'left_low' 'no']
 ['40-49' 'premeno' '50-54' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['40-49' 'premeno' '20-24' '0-2' 'no' 2 'right' 'left_up' 'no']
 ['40-49' 'premeno' '0-4' '0-2' 'no' 3 'left' 'central' 'no']
 ['50-59' 'ge40' '25-29' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['60-69' 'lt40' '10-14' '0-2' 'no' 1 'left' 'right_up' 'no']
 ['50-59' 'ge40' '25-29' '0-2' 'no' 3 'left' 'right_up' 'no']
 ['40-49' 'premeno' '30-34' '0-2' 'no' 3 'left' 'left_up' 'no']
 ['60-69' 'lt40' '30-34' '0-2'

In [15]:
x_primary_tumor = df_primary_tumor[["age", "sex", "histologic-type", "degree-of-diffe", "bone", "bone-marrow", "lung",
                     "pleura", "peritoneum", "liver", "brain", "skin", "neck", "supraclavicular", "axillar", 
                    "mediastinum", "abdomnial"]].to_numpy()
y_primary_tumor = df_primary_tumor["class"].to_numpy()

print("X_primary_tumor", x_primary_tumor[:20, :])
print("Y_primary_tumor", y_primary_tumor[:20])

X_primary_tumor [[1. 1. 2. 3. 2. 2. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 2. 3. 2. 2. 2. 2. 2. 1. 2. 2. 2. 1. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 2. 2. 2. 2. 1. 2. 2. 1. 1. 1. 2.]
 [2. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 1. 1. 1. 2. 2. 2.]
 [2. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2. 2. 2. 2.]
 [2. 1. 1. 2. 1. 2. 2. 2. 2. 2. 2. 2. 1. 1. 2. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 1. 2. 2. 2. 2. 2. 1. 2. 1. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 1. 2. 2. 1. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 3. 2. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 1. 2.]
 [2. 1. 1. 2. 2. 2. 2. 1. 2. 1. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2. 1. 2.]
 [2. 1. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 1. 1. 2. 1. 2.]
 [2. 1. 2. 3

In [16]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

iris = load_iris()
X = iris.data
y = iris.target

print(X[:200,:])
print(y[:200])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.