<font color = Magenta> _Lixandru Andreea-Bianca 382
 <br>   Pepene Adina-Florentina 382_

# Laborator 6

Versiunea 2020-04-01

## Modele de clasificare

Folositi 4 seturi de date pentru probleme de clasificare, plecand de la repository-urile specificate in Cursul 5; de exemplu, [ics.uci.edu](http://archive.ics.uci.edu/ml/datasets.php?format=mat&task=cla&att=&area=&numAtt=&numIns=&type=mvar&sort=nameUp&view=table). Cel putin doua seturi de date sa fie cu valori lipsa. 


1. (20 puncte) Aplicati o metoda de missing value imputation, unde este cazul; justificati si documentati metoda folosita.
1. (numar de modele * numar de seturi de date \* 1 punct = 20 de puncte) Pentru fiecare set de date aplicati 5 modele de clasificare din scikit learn. Pentru fiecare raportati: acuratete, scorul F1 - a se vedea [sklearn.metrics](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) - folosind 5 fold cross validation. Raportati mediile rezultatelor atat pentru fold-urile de antrenare, cat si pentru cele de testare. Rularile se vor face cu valori fixate ale hiperparametrilor. 
1. (numar modele * 4 puncte = 20 puncte) Documentati in jupyter notebook fiecare din modelele folosite, in limba romana. Daca acelasi algoritm e folosit pentru mai multe seturi de date, puteti face o sectiune separata cu documentarea algoritmilor + trimitere la algoritm. 
1. (numar de modele * numar de seturi de date * 1 punct = 20 de puncte) Raportati performanta fiecarui model, folosind 5 fold cross validation. Pentru fiecare din cele 5 rulari, cautati hiperparametrii optimi folosind 4-fold cross validation. Performanta modelului va fi raportata ca medie a celor  5 rulari. 
    *Observatie:* la fiecare din cele 5 rulari, hiperparametrii optimi pot diferi, din cauza datelor utilizate pentru antrenare/validare.  

Se acorda 20 de puncte din oficiu. 

Exemple de modele de clasificare:
1. [Multi-layer Perceptron classifier](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier)
1. [KNN](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier)
1. [SVM](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC)
1. [Gaussian processes](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html#sklearn.gaussian_process.GaussianProcessClassifier)
1. [RBF](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.RBF.html#sklearn.gaussian_process.kernels.RBF)
1. [Decision tree](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier)
1. [Random forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier)
1. [Gaussian Naive bayes](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB) 

*Predare:* 
1. Fiecare student va depune pe site-ul de elearning fisier Jupyter notebook sau arhiva cu astfel de fisiere; 
1. In fiecare fisier se specifica numele celor doi studenti care au lucra in echipa. 
1. Predarea se face in saptamana 13-17 aprilie 2020
1. Revedeti formele ulterioare ale acestui document pentru precizari despre: continutul rezultatelor raportate, modalitate de notare.

# <font color= Magenta> Rezolvare

<font color=blue>Ex1:</font> Aplicati o metoda de missing value imputation, unde este cazul; justificati si documentati metoda folosita.
<br>
><br>Metode posibile:
<br>1. Eliminarea liniilor care contin valori nan.
<br>2. Eliminarea coloanelor care contin nan.
<br>3. Umplerea valorilor nan cu:
> -> o valoare constanta
><br>-> copierea ultimei valori cunoscute(ffill)
><br>-> umplere 'inapoi'(bfill)
><br>-> o valoare calculata (ex: media)

Citim seturile de date si ne uitam care dintre ele au valori lipsa.

In [1]:
import pandas as pd 
import numpy as np

In [2]:
names_yeast = ["mcg", "gvh","alm","mit","erl","pox","vac","nuc","class"]

df_yeast = pd.read_csv('./data/yeast/yeast.data',sep=r" +", engine="python", names=names_yeast)

df_yeast.head()

mcg   gvh   alm   mit  erl  pox   vac   nuc class
ADT1_YEAST  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22   MIT
ADT2_YEAST  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22   MIT
ADT3_YEAST  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22   MIT
AAR2_YEAST  0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22   NUC
AATM_YEAST  0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22   MIT

In [3]:
df_yeast.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1484 entries, ADT1_YEAST to G6PD_YEAST
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   mcg     1484 non-null   float64
 1   gvh     1484 non-null   float64
 2   alm     1484 non-null   float64
 3   mit     1484 non-null   float64
 4   erl     1484 non-null   float64
 5   pox     1484 non-null   float64
 6   vac     1484 non-null   float64
 7   nuc     1484 non-null   float64
 8   class   1484 non-null   object 
dtypes: float64(8), object(1)
memory usage: 115.9+ KB


In [4]:
df_wine = pd.read_csv('./data/wine/winequality-red.csv', sep=';')

df_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [6]:
names_mammographics = ["BI-RADS","Age","Shape","Margin","Density","Severity"]

df_mammographics = pd.read_csv('./data/mammographic/mammographic_masses.data', names=names_mammographics)

df_mammographics.head()

BI-RADS Age Shape Margin Density  Severity
0       5  67     3      5       3         1
1       4  43     1      1       ?         1
2       5  58     4      5       3         1
3       4  28     1      1       3         0
4       5  74     1      5       ?         1

In [7]:
'''Valorile din data frame care lipsesc sunt marcate cu '?'.
Ca sa putem vedea cate valori lipsesc trebuie sa inlocuim
toate valorile '?' cu valoarea nan. '''

df_mammographics = df_mammographics.replace('?', np.nan)
df_mammographics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   BI-RADS   959 non-null    object
 1   Age       956 non-null    object
 2   Shape     930 non-null    object
 3   Margin    913 non-null    object
 4   Density   885 non-null    object
 5   Severity  961 non-null    int64 
dtypes: int64(1), object(5)
memory usage: 45.2+ KB


In [8]:
'''Exista mai multe metode prin care putem umple valorile lipsa 
am ales umplerea valorilor prin copierea ultimei valori cunoscute.'''

df_mammographics = df_mammographics.fillna(method='ffill')

df_mammographics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   BI-RADS   961 non-null    object
 1   Age       961 non-null    object
 2   Shape     961 non-null    object
 3   Margin    961 non-null    object
 4   Density   961 non-null    object
 5   Severity  961 non-null    int64 
dtypes: int64(1), object(5)
memory usage: 45.2+ KB


In [9]:
df_mammographics.head()

BI-RADS Age Shape Margin Density  Severity
0       5  67     3      5       3         1
1       4  43     1      1       3         1
2       5  58     4      5       3         1
3       4  28     1      1       3         0
4       5  74     1      5       3         1

In [10]:
df_mammographics = pd.get_dummies(df_mammographics, columns=["Shape", "Margin"])

df_mammographics.head()

BI-RADS Age Density  Severity  Shape_1  Shape_2  Shape_3  Shape_4  Margin_1  \
0       5  67       3         1        0        0        1        0         0   
1       4  43       3         1        1        0        0        0         1   
2       5  58       3         1        0        0        0        1         0   
3       4  28       3         0        1        0        0        0         1   
4       5  74       3         1        1        0        0        0         0   

   Margin_2  Margin_3  Margin_4  Margin_5  
0         0         0         0         1  
1         0         0         0         0  
2         0         0         0         1  
3         0         0         0         0  
4         0         0         0         1

In [11]:
names_breast_cancer = ["class","age","menopause","tumor-size","inv-nodes","node-caps","deg-malig",
                       "breast","breast-quad","irradiat"]

df_breast_cancer = pd.read_csv('./data/breast_cancer/breast-cancer.data', names=names_breast_cancer)

df_breast_cancer.head()

class    age menopause tumor-size inv-nodes node-caps  \
0  no-recurrence-events  30-39   premeno      30-34       0-2        no   
1  no-recurrence-events  40-49   premeno      20-24       0-2        no   
2  no-recurrence-events  40-49   premeno      20-24       0-2        no   
3  no-recurrence-events  60-69      ge40      15-19       0-2        no   
4  no-recurrence-events  40-49   premeno        0-4       0-2        no   

   deg-malig breast breast-quad irradiat  
0          3   left    left_low       no  
1          2  right    right_up       no  
2          2   left    left_low       no  
3          2  right     left_up       no  
4          2  right   right_low       no

In [12]:
'''In data set-ul breast_cancer missing values sunt marcate prin '?',
nu prin valori NaN, asa ca dorim sa inlocuim  valorile '?' cu valori
NaN astfel incat sa putem vedea cre sunt valorile necompletate si
sa le putem inlocui sau sterge.'''

df_breast_cancer = df_breast_cancer.replace('?', np.nan)
df_breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   class        286 non-null    object
 1   age          286 non-null    object
 2   menopause    286 non-null    object
 3   tumor-size   286 non-null    object
 4   inv-nodes    286 non-null    object
 5   node-caps    278 non-null    object
 6   deg-malig    286 non-null    int64 
 7   breast       286 non-null    object
 8   breast-quad  285 non-null    object
 9   irradiat     286 non-null    object
dtypes: int64(1), object(9)
memory usage: 22.5+ KB


In [13]:
names_primary_tumor =["class","age","sex","histologic-type","degree-of-diffe","bone","bone-marrow","lung",
                     "pleura","peritoneum","liver","brain","skin","neck","supraclavicular","axillar","mediastinum","abdomnial"]

df_primary_tumor = pd.read_csv("./data/primary_tumor/primary-tumor.data", names=names_primary_tumor)

df_primary_tumor.head()

class  age sex histologic-type degree-of-diffe  bone  bone-marrow  lung  \
0      1    1   1               ?               3     2            2     1   
1      1    1   1               ?               3     2            2     2   
2      1    1   2               2               3     1            2     2   
3      1    1   2               ?               3     1            2     1   
4      1    1   2               ?               3     1            2     1   

   pleura  peritoneum  liver  brain skin  neck  supraclavicular axillar  \
0       2           2      2      2    2     2                2       2   
1       2           2      1      2    2     2                1       2   
2       2           2      2      2    2     2                2       2   
3       1           2      2      2    2     2                2       2   
4       1           2      2      2    2     2                2       2   

   mediastinum  abdomnial  
0            2          2  
1            1          2  
2            1          2  
3            1          2  
4            1          2

In [14]:
df_primary_tumor = df_primary_tumor.replace('?', np.nan)

df_primary_tumor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   class            339 non-null    int64 
 1   age              339 non-null    int64 
 2   sex              338 non-null    object
 3   histologic-type  272 non-null    object
 4   degree-of-diffe  184 non-null    object
 5   bone             339 non-null    int64 
 6   bone-marrow      339 non-null    int64 
 7   lung             339 non-null    int64 
 8   pleura           339 non-null    int64 
 9   peritoneum       339 non-null    int64 
 10  liver            339 non-null    int64 
 11  brain            339 non-null    int64 
 12  skin             338 non-null    object
 13  neck             339 non-null    int64 
 14  supraclavicular  339 non-null    int64 
 15  axillar          338 non-null    object
 16  mediastinum      339 non-null    int64 
 17  abdomnial        339 non-null    in

In [15]:
'''Pentru dataset-ul breast_cancer am ales sa umplem valorile nan
prin copierea ultimei valori cunoscute, intrucat am dori sa pastram
cat mai multe din liniile si coloanele data set-ului nostru.
Pe coloanele care lipsesc valori nu exista o varietate mare de valori,
deci putem folosi ultima valoare cunoscuta. Setul de date este aproape
complet si nu necesita multe adaugari.'''

df_breast_cancer = df_breast_cancer.fillna(method='ffill')

df_breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   class        286 non-null    object
 1   age          286 non-null    object
 2   menopause    286 non-null    object
 3   tumor-size   286 non-null    object
 4   inv-nodes    286 non-null    object
 5   node-caps    286 non-null    object
 6   deg-malig    286 non-null    int64 
 7   breast       286 non-null    object
 8   breast-quad  286 non-null    object
 9   irradiat     286 non-null    object
dtypes: int64(1), object(9)
memory usage: 22.5+ KB


In [16]:
df_breast_cancer_2 = pd.get_dummies(df_breast_cancer, columns=["age", "menopause", "tumor-size", "inv-nodes", "deg-malig",
                                                              "breast-quad"])

df_breast_cancer_2.head()

class node-caps breast irradiat  age_20-29  age_30-39  \
0  no-recurrence-events        no   left       no          0          1   
1  no-recurrence-events        no  right       no          0          0   
2  no-recurrence-events        no   left       no          0          0   
3  no-recurrence-events        no  right       no          0          0   
4  no-recurrence-events        no  right       no          0          0   

   age_40-49  age_50-59  age_60-69  age_70-79  ...  inv-nodes_6-8  \
0          0          0          0          0  ...              0   
1          1          0          0          0  ...              0   
2          1          0          0          0  ...              0   
3          0          0          1          0  ...              0   
4          1          0          0          0  ...              0   

   inv-nodes_9-11  deg-malig_1  deg-malig_2  deg-malig_3  breast-quad_central  \
0               0            0            0            1                    0   
1               0            0            1            0                    0   
2               0            0            1            0                    0   
3               0            0            1            0                    0   
4               0            0            1            0                    0   

   breast-quad_left_low  breast-quad_left_up  breast-quad_right_low  \
0                     1                    0                      0   
1                     0                    0                      0   
2                     1                    0                      0   
3                     0                    1                      0   
4                     0                    0                      1   

   breast-quad_right_up  
0                     0  
1                     1  
2                     0  
3                     0  
4                     0  

[5 rows x 39 columns]

In [17]:
'''Pentru dataset-ul primary_tumor am ales sa umplem valorile lipsa
cu media de pe coloana, intrucat am observat ca lipsesc multe valori 
de pe aceeasi coloana, deci nu putem avea o evidenta clara asupra
datelor anterioare. Totusi, nu putem decide inca daca renuntam
la coloana digree-of-diffe. Ramane de vazut...'''

df_primary_tumor = df_primary_tumor.apply(lambda x: pd.to_numeric(x), axis=0)

df_primary_tumor = df_primary_tumor.fillna(round(df_primary_tumor.mean()))

df_primary_tumor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   class            339 non-null    int64  
 1   age              339 non-null    int64  
 2   sex              339 non-null    float64
 3   histologic-type  339 non-null    float64
 4   degree-of-diffe  339 non-null    float64
 5   bone             339 non-null    int64  
 6   bone-marrow      339 non-null    int64  
 7   lung             339 non-null    int64  
 8   pleura           339 non-null    int64  
 9   peritoneum       339 non-null    int64  
 10  liver            339 non-null    int64  
 11  brain            339 non-null    int64  
 12  skin             339 non-null    float64
 13  neck             339 non-null    int64  
 14  supraclavicular  339 non-null    int64  
 15  axillar          339 non-null    float64
 16  mediastinum      339 non-null    int64  
 17  abdomnial       

<font color=blue>Ex2:</font> Pentru fiecare set de date aplicati 5 modele de clasificare din scikit learn. Pentru fiecare raportati: acuratete, scorul F1 - a se vedea sklearn.metrics - folosind 5 fold cross validation. Raportati mediile rezultatelor atat pentru fold-urile de antrenare, cat si pentru cele de testare. Rularile se vor face cu valori fixate ale hiperparametrilor.

Trebuie sa separam datele in date de intrare si date de iesire.

In [18]:
x_yeast = df_yeast[["mcg", "gvh", "alm", "mit", "erl", "pox", "vac","nuc"]].to_numpy()
y_yeast = df_yeast["class"].to_numpy()

print("X_yeast", x_yeast[:20, :])
print("Y_yeast", y_yeast[:20])

X_yeast [[0.58 0.61 0.47 0.13 0.5  0.   0.48 0.22]
 [0.43 0.67 0.48 0.27 0.5  0.   0.53 0.22]
 [0.64 0.62 0.49 0.15 0.5  0.   0.53 0.22]
 [0.58 0.44 0.57 0.13 0.5  0.   0.54 0.22]
 [0.42 0.44 0.48 0.54 0.5  0.   0.48 0.22]
 [0.51 0.4  0.56 0.17 0.5  0.5  0.49 0.22]
 [0.5  0.54 0.48 0.65 0.5  0.   0.53 0.22]
 [0.48 0.45 0.59 0.2  0.5  0.   0.58 0.34]
 [0.55 0.5  0.66 0.36 0.5  0.   0.49 0.22]
 [0.4  0.39 0.6  0.15 0.5  0.   0.58 0.3 ]
 [0.43 0.39 0.54 0.21 0.5  0.   0.53 0.27]
 [0.42 0.37 0.59 0.2  0.5  0.   0.52 0.29]
 [0.4  0.42 0.57 0.35 0.5  0.   0.53 0.25]
 [0.6  0.4  0.52 0.46 0.5  0.   0.53 0.22]
 [0.66 0.55 0.45 0.19 0.5  0.   0.46 0.22]
 [0.46 0.44 0.52 0.11 0.5  0.   0.5  0.22]
 [0.47 0.39 0.5  0.11 0.5  0.   0.49 0.4 ]
 [0.58 0.47 0.54 0.11 0.5  0.   0.51 0.26]
 [0.5  0.34 0.55 0.21 0.5  0.   0.49 0.22]
 [0.61 0.6  0.55 0.21 0.5  0.   0.5  0.25]]
Y_yeast ['MIT' 'MIT' 'MIT' 'NUC' 'MIT' 'CYT' 'MIT' 'NUC' 'MIT' 'CYT' 'NUC' 'NUC'
 'CYT' 'MIT' 'MIT' 'CYT' 'CYT' 'NUC' 'NUC' 'NUC']


In [19]:
x_wine = df_wine [["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", 
                   "free sulfur dioxide", "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]].to_numpy()
y_wine = df_wine["quality"].to_numpy()

print("X_wine", x_wine[:20, :])
print("Y_wine", y_wine[:20])

X_wine [[7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00]
 [7.800e+00 7.600e-01 4.000e-02 2.300e+00 9.200e-02 1.500e+01 5.400e+01
  9.970e-01 3.260e+00 6.500e-01 9.800e+00]
 [1.120e+01 2.800e-01 5.600e-01 1.900e+00 7.500e-02 1.700e+01 6.000e+01
  9.980e-01 3.160e+00 5.800e-01 9.800e+00]
 [7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.400e+00 6.600e-01 0.000e+00 1.800e+00 7.500e-02 1.300e+01 4.000e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00]
 [7.300e+00 6.500e-01 0.000e+00 1.200e+00 6.500e-02 1.500e+01 2.100e+01
  9.946e-01 3.390e+00 4.700e-01 1.000e+01]
 [7.800e+00 5.800e-01 2.000e-02 2.000e+00 7.300e-02 9.000e+00 1.800e+01
 

In [20]:
x_mammographic = df_mammographics[["BI-RADS","Age",
                                   "Shape_1","Shape_2","Shape_3","Shape_4",
                                   "Margin_1","Margin_2","Margin_3","Margin_4","Margin_5",
                                   "Density"]].to_numpy()

y_mammographic = df_mammographics["Severity"].to_numpy()

In [21]:
x_breast_cancer = df_breast_cancer[["age", "menopause", "tumor-size", "inv-nodes", "node-caps", "deg-malig", "breast", 
                                    "breast-quad", "irradiat"]].to_numpy()
y_breast_cancer = df_breast_cancer["class"].to_numpy()

print("X_breast_cancer", x_breast_cancer[:20, :])
print("Y_breast_cancer", y_breast_cancer[:20])

X_breast_cancer [['30-39' 'premeno' '30-34' '0-2' 'no' 3 'left' 'left_low' 'no']
 ['40-49' 'premeno' '20-24' '0-2' 'no' 2 'right' 'right_up' 'no']
 ['40-49' 'premeno' '20-24' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['60-69' 'ge40' '15-19' '0-2' 'no' 2 'right' 'left_up' 'no']
 ['40-49' 'premeno' '0-4' '0-2' 'no' 2 'right' 'right_low' 'no']
 ['60-69' 'ge40' '15-19' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['50-59' 'premeno' '25-29' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['60-69' 'ge40' '20-24' '0-2' 'no' 1 'left' 'left_low' 'no']
 ['40-49' 'premeno' '50-54' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['40-49' 'premeno' '20-24' '0-2' 'no' 2 'right' 'left_up' 'no']
 ['40-49' 'premeno' '0-4' '0-2' 'no' 3 'left' 'central' 'no']
 ['50-59' 'ge40' '25-29' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['60-69' 'lt40' '10-14' '0-2' 'no' 1 'left' 'right_up' 'no']
 ['50-59' 'ge40' '25-29' '0-2' 'no' 3 'left' 'right_up' 'no']
 ['40-49' 'premeno' '30-34' '0-2' 'no' 3 'left' 'left_up' 'no']
 ['60-69' 'lt40' '30-34' '0-2'

In [22]:
x_primary_tumor = df_primary_tumor[["age", "sex", "histologic-type", "degree-of-diffe", "bone", "bone-marrow", "lung",
                     "pleura", "peritoneum", "liver", "brain", "skin", "neck", "supraclavicular", "axillar", 
                    "mediastinum", "abdomnial"]].to_numpy()
y_primary_tumor = df_primary_tumor["class"].to_numpy()

print("X_primary_tumor", x_primary_tumor[:20, :])
print("Y_primary_tumor", y_primary_tumor[:20])

X_primary_tumor [[1. 1. 2. 3. 2. 2. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 2. 3. 2. 2. 2. 2. 2. 1. 2. 2. 2. 1. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 2. 2. 2. 2. 1. 2. 2. 1. 1. 1. 2.]
 [2. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 1. 1. 1. 2. 2. 2.]
 [2. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2. 2. 2. 2.]
 [2. 1. 1. 2. 1. 2. 2. 2. 2. 2. 2. 2. 1. 1. 2. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 1. 2. 2. 2. 2. 2. 1. 2. 1. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 1. 2. 2. 1. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 3. 2. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 1. 2.]
 [2. 1. 1. 2. 2. 2. 2. 1. 2. 1. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2. 1. 2.]
 [2. 1. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 1. 1. 2. 1. 2.]
 [2. 1. 2. 3

Separam setul de date in set de antrenare si set de testare.
<br> Cand folosim random state facem un random mai stabil.

# <font color=magenta> 1. KNeighbourClassifier

In [51]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score

In [109]:
def k_neighbours_method(X, y, number_of_neighbors) -> None:
    
#     model = KNeighborsClassifier(n_neighbors=number_of_neighbors)
    
#     scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')
    
#     print(scores.mean())

    for i in range(5):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
    
        model = KNeighborsClassifier(n_neighbors = number_of_neighbors)
        model.fit(X_train, y_train)
    
        y_predicated_train = model.predict(X_train)
        y_predicated_test = model.predict(X_test)
    
        print ("Iteration:", i)
        print ("Train score:", model.score(X_train, y_train)*100)
        print ("Test score:", model.score(X_test, y_test)*100)
        print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
        print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
        print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
        # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
        print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
        print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
        print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
        print ()

In [110]:
k_neighbours_method_2(x_yeast, y_yeast, 59)

Iteration: 0
Train score: 59.25176946410515
Test score: 58.38383838383838
Different outputs train: 403 from total of 989
Different outputs test: 206 from total of 495
Accuracy train: 59.25176946410515
F1-score train: 59.25176946410515
Accuracy test: 58.38383838383838
F1-score test: 58.38383838383838

Iteration: 1
Train score: 59.04954499494439
Test score: 55.959595959595966
Different outputs train: 405 from total of 989
Different outputs test: 218 from total of 495
Accuracy train: 59.04954499494439
F1-score train: 59.04954499494439
Accuracy test: 55.959595959595966
F1-score test: 55.959595959595966

Iteration: 2
Train score: 57.93731041456016
Test score: 57.77777777777777
Different outputs train: 416 from total of 989
Different outputs test: 209 from total of 495
Accuracy train: 57.93731041456016
F1-score train: 57.93731041456016
Accuracy test: 57.77777777777777
F1-score test: 57.77777777777777

Iteration: 3
Train score: 57.83619817997978
Test score: 57.77777777777777
Different outputs

In [41]:
k_neighbours_method_2(x_wine, y_wine, 73)

Iteration: 0
Train score: 51.12570356472796
Test score: 54.409005628517825
Different outputs train: 521 from total of 1066
Different outputs test: 243 from total of 533
Accuracy train: 51.12570356472796
F1-score train: 51.12570356472796
Accuracy test: 54.409005628517825
F1-score test: 54.409005628517825

Iteration: 1
Train score: 54.315196998123824
Test score: 50.28142589118198
Different outputs train: 487 from total of 1066
Different outputs test: 265 from total of 533
Accuracy train: 54.315196998123824
F1-score train: 54.315196998123824
Accuracy test: 50.28142589118198
F1-score test: 50.28142589118198

Iteration: 2
Train score: 53.189493433395874
Test score: 48.21763602251407
Different outputs train: 499 from total of 1066
Different outputs test: 276 from total of 533
Accuracy train: 53.189493433395874
F1-score train: 53.189493433395874
Accuracy test: 48.21763602251407
F1-score test: 48.21763602251407

Iteration: 3
Train score: 51.21951219512195
Test score: 50.28142589118198
Differen

In [50]:
k_neighbours_method_2(x_mammographic, y_mammographic, 10)

Iteration: 0
Train score: 82.03125
Test score: 81.93146417445483
Different outputs train: 115 from total of 640
Different outputs test: 58 from total of 321
Accuracy train: 82.03125
F1-score train: 82.03125
Accuracy test: 81.93146417445483
F1-score test: 81.93146417445482

Iteration: 1
Train score: 82.1875
Test score: 77.25856697819314
Different outputs train: 114 from total of 640
Different outputs test: 73 from total of 321
Accuracy train: 82.1875
F1-score train: 82.1875
Accuracy test: 77.25856697819314
F1-score test: 77.25856697819314

Iteration: 2
Train score: 81.25
Test score: 80.37383177570094
Different outputs train: 120 from total of 640
Different outputs test: 63 from total of 321
Accuracy train: 81.25
F1-score train: 81.25
Accuracy test: 80.37383177570094
F1-score test: 80.37383177570094

Iteration: 3
Train score: 82.5
Test score: 81.93146417445483
Different outputs train: 112 from total of 640
Different outputs test: 58 from total of 321
Accuracy train: 82.5
F1-score train: 

# <font color=Magenta> 2. MLPClassifier

In [56]:
from sklearn.neural_network import MLPClassifier

In [57]:
def mlp_method(X, y, activ) -> None:
    #‘sgd’ refers to stochastic gradient descent.
    
    for i in range(5):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
        model =  MLPClassifier(activation = activ, random_state = 10)
        model.fit(X_train, y_train)
    
        y_predicated_train = model.predict(X_train)
        y_predicated_test = model.predict(X_test)
    
        print ("Iteration:", i)
        print ("Train score:", model.score(X_train, y_train)*100)
        print ("Test score:", model.score(X_test, y_test)*100)
        print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
        print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
        print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
        # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
        print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
        print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
        print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
        print ()

In [59]:
mlp_method (x_yeast, y_yeast, 'tanh')

D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration: 0
Train score: 60.06066734074823
Test score: 58.38383838383838
Different outputs train: 395 from total of 989
Different outputs test: 206 from total of 495
Accuracy train: 60.06066734074823
F1-score train: 60.06066734074823
Accuracy test: 58.38383838383838
F1-score test: 58.38383838383838



D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration: 1
Train score: 59.95955510616785
Test score: 55.959595959595966
Different outputs train: 396 from total of 989
Different outputs test: 218 from total of 495
Accuracy train: 59.95955510616785
F1-score train: 59.95955510616785
Accuracy test: 55.959595959595966
F1-score test: 55.959595959595966



D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration: 2
Train score: 58.54398382204246
Test score: 57.97979797979798
Different outputs train: 410 from total of 989
Different outputs test: 208 from total of 495
Accuracy train: 58.54398382204246
F1-score train: 58.54398382204246
Accuracy test: 57.97979797979798
F1-score test: 57.97979797979798



D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration: 3
Train score: 57.43174924165824
Test score: 58.18181818181818
Different outputs train: 421 from total of 989
Different outputs test: 207 from total of 495
Accuracy train: 57.43174924165824
F1-score train: 57.43174924165824
Accuracy test: 58.18181818181818
F1-score test: 58.18181818181818

Iteration: 4
Train score: 60.16177957532861
Test score: 51.91919191919192
Different outputs train: 394 from total of 989
Different outputs test: 238 from total of 495
Accuracy train: 60.16177957532861
F1-score train: 60.16177957532861
Accuracy test: 51.91919191919192
F1-score test: 51.91919191919192



D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [60]:
mlp_method (x_wine, y_wine, 'tanh')

D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration: 0
Train score: 60.31894934333959
Test score: 61.72607879924953
Different outputs train: 423 from total of 1066
Different outputs test: 204 from total of 533
Accuracy train: 60.31894934333959
F1-score train: 60.31894934333959
Accuracy test: 61.72607879924953
F1-score test: 61.72607879924953



D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration: 1
Train score: 60.131332082551594
Test score: 60.60037523452158
Different outputs train: 425 from total of 1066
Different outputs test: 210 from total of 533
Accuracy train: 60.131332082551594
F1-score train: 60.131332082551594
Accuracy test: 60.60037523452158
F1-score test: 60.60037523452158



D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration: 2
Train score: 62.38273921200751
Test score: 56.28517823639775
Different outputs train: 401 from total of 1066
Different outputs test: 233 from total of 533
Accuracy train: 62.38273921200751
F1-score train: 62.38273921200751
Accuracy test: 56.28517823639775
F1-score test: 56.28517823639775



D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration: 3
Train score: 61.81988742964353
Test score: 56.84803001876173
Different outputs train: 407 from total of 1066
Different outputs test: 230 from total of 533
Accuracy train: 61.81988742964353
F1-score train: 61.81988742964353
Accuracy test: 56.84803001876173
F1-score test: 56.84803001876173

Iteration: 4
Train score: 62.38273921200751
Test score: 58.348968105065666
Different outputs train: 401 from total of 1066
Different outputs test: 222 from total of 533
Accuracy train: 62.38273921200751
F1-score train: 62.38273921200751
Accuracy test: 58.348968105065666
F1-score test: 58.348968105065666



D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [62]:
mlp_method (x_mammographic, y_mammographic, 'tanh')

Iteration: 0
Train score: 81.40625
Test score: 80.99688473520249
Different outputs train: 119 from total of 640
Different outputs test: 61 from total of 321
Accuracy train: 81.40625
F1-score train: 81.40625
Accuracy test: 80.99688473520249
F1-score test: 80.99688473520249

Iteration: 1
Train score: 82.65625
Test score: 78.81619937694704
Different outputs train: 111 from total of 640
Different outputs test: 68 from total of 321
Accuracy train: 82.65625
F1-score train: 82.65625
Accuracy test: 78.81619937694704
F1-score test: 78.81619937694704



D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration: 2
Train score: 81.25
Test score: 82.2429906542056
Different outputs train: 120 from total of 640
Different outputs test: 57 from total of 321
Accuracy train: 81.25
F1-score train: 81.25
Accuracy test: 82.2429906542056
F1-score test: 82.2429906542056

Iteration: 3
Train score: 81.09375
Test score: 80.37383177570094
Different outputs train: 121 from total of 640
Different outputs test: 63 from total of 321
Accuracy train: 81.09375
F1-score train: 81.09375
Accuracy test: 80.37383177570094
F1-score test: 80.37383177570094

Iteration: 4
Train score: 82.34375
Test score: 79.12772585669782
Different outputs train: 113 from total of 640
Different outputs test: 67 from total of 321
Accuracy train: 82.34375
F1-score train: 82.34375
Accuracy test: 79.12772585669782
F1-score test: 79.12772585669782



In [ ]:
mlp_method(X_train_yeast, y_train_yeast, X_test_yeast, y_test_yeast, 'tanh')

# Train score: 59.45399393326593 #solver='adam'
# Test score: 61.41414141414141
# Different outputs train: 401 from total of 989
# Different outputs test: 191 from total of 495

# Train score: 62.588473205257834 #solver='lbfgs'
# Test score: 61.41414141414141
# Different outputs train: 370 from total of 989
# Different outputs test: 191 from total of 495

In [ ]:
mlp_method(X_train_wine, y_train_wine, X_test_wine, y_test_wine, 'tanh')

# Train score: 62.7579737335835 #solver='adam'
# Test score: 53.09568480300187
# Different outputs train: 397 from total of 1066
# Different outputs test: 250 from total of 533

# Train score: 65.94746716697935 #solver='lbfgs'
# Test score: 54.971857410881796
# Different outputs train: 363 from total of 1066
# Different outputs test: 240 from total of 533

In [ ]:
mlp_method(X_train_breast_cancer, y_train_breast_cancer, X_test_breast_cancer, y_test_breast_cancer, 'relu')

# Train score: 78.94736842105263 #solver='adam'
# Test score: 73.95833333333334
# Different outputs train: 40 from total of 190
# Different outputs test: 25 from total of 96

# Train score: 78.94736842105263 #solver='lbfgs'
# Test score: 68.75
# Different outputs train: 40 from total of 190
# Different outputs test: 30 from total of 96

In [ ]:
mlp_method(X_train_primary_tumor, y_train_primary_tumor, X_test_primary_tumor, y_test_primary_tumor, 'identity')

# Train score: 56.19469026548673 #solver='adam'
# Test score: 42.47787610619469
# Different outputs train: 99 from total of 226
# Different outputs test: 65 from total of 113

# Train score: 66.3716814159292 #solver='lbfgs'
# Test score: 38.93805309734513
# Different outputs train: 76 from total of 226
# Different outputs test: 69 from total of 113

# <font color=Magenta> 3. SVC

In [63]:
from sklearn.svm import SVC

In [64]:
def svc_method(X, y) -> None:
    
    for i in range(5):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
        model = SVC(class_weight=None, random_state = 10)
        model.fit(X_train,y_train)
    
        y_predicated_train = model.predict(X_train)
        y_predicated_test = model.predict(X_test)
    
        print ("Iteration:", i)
        print ("Train score:", model.score(X_train, y_train)*100)
        print ("Test score:", model.score(X_test, y_test)*100)
        print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
        print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
        print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
        # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
        print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
        print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
        print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
        print ()

In [66]:
svc_method (x_yeast, y_yeast)

Iteration: 0
Train score: 61.071789686552066
Test score: 58.98989898989899
Different outputs train: 385 from total of 989
Different outputs test: 203 from total of 495
Accuracy train: 61.071789686552066
F1-score train: 61.071789686552066
Accuracy test: 58.98989898989899
F1-score test: 58.98989898989899

Iteration: 1
Train score: 62.28513650151668
Test score: 56.96969696969697
Different outputs train: 373 from total of 989
Different outputs test: 213 from total of 495
Accuracy train: 62.28513650151668
F1-score train: 62.28513650151668
Accuracy test: 56.96969696969697
F1-score test: 56.96969696969697

Iteration: 2
Train score: 62.1840242669363
Test score: 59.59595959595959
Different outputs train: 374 from total of 989
Different outputs test: 200 from total of 495
Accuracy train: 62.1840242669363
F1-score train: 62.1840242669363
Accuracy test: 59.59595959595959
F1-score test: 59.59595959595959

Iteration: 3
Train score: 61.071789686552066
Test score: 60.80808080808081
Different outputs t

In [67]:
svc_method (x_wine, y_wine)

Iteration: 0
Train score: 49.62476547842402
Test score: 51.594746716697934
Different outputs train: 537 from total of 1066
Different outputs test: 258 from total of 533
Accuracy train: 49.62476547842402
F1-score train: 49.62476547842402
Accuracy test: 51.594746716697934
F1-score test: 51.594746716697934

Iteration: 1
Train score: 50.84427767354597
Test score: 50.65666041275797
Different outputs train: 524 from total of 1066
Different outputs test: 263 from total of 533
Accuracy train: 50.84427767354597
F1-score train: 50.84427767354597
Accuracy test: 50.65666041275797
F1-score test: 50.65666041275797

Iteration: 2
Train score: 50.562851782363985
Test score: 53.09568480300187
Different outputs train: 527 from total of 1066
Different outputs test: 250 from total of 533
Accuracy train: 50.562851782363985
F1-score train: 50.562851782363985
Accuracy test: 53.09568480300187
F1-score test: 53.09568480300187

Iteration: 3
Train score: 51.594746716697934
Test score: 48.96810506566604
Different 

In [68]:
svc_method (x_mammographic, y_mammographic)

Iteration: 0
Train score: 70.46875
Test score: 69.78193146417445
Different outputs train: 189 from total of 640
Different outputs test: 97 from total of 321
Accuracy train: 70.46875
F1-score train: 70.46875
Accuracy test: 69.78193146417445
F1-score test: 69.78193146417445

Iteration: 1
Train score: 69.84375
Test score: 69.1588785046729
Different outputs train: 193 from total of 640
Different outputs test: 99 from total of 321
Accuracy train: 69.84375
F1-score train: 69.84375
Accuracy test: 69.1588785046729
F1-score test: 69.1588785046729

Iteration: 2
Train score: 70.15625
Test score: 69.47040498442367
Different outputs train: 191 from total of 640
Different outputs test: 98 from total of 321
Accuracy train: 70.15625
F1-score train: 70.15625
Accuracy test: 69.47040498442367
F1-score test: 69.47040498442367

Iteration: 3
Train score: 69.53125
Test score: 69.78193146417445
Different outputs train: 195 from total of 640
Different outputs test: 97 from total of 321
Accuracy train: 69.53125

# <font color = magenta> 4. GaussianProcessClassifier

In [69]:
from sklearn.gaussian_process import GaussianProcessClassifier

In [77]:
def gaussian_method(X, y) -> None:
    
    for i in range(5):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
        model = GaussianProcessClassifier(random_state = 10)
        model.fit(X_train, y_train)
    
        y_predicated_train = model.predict(X_train)
        y_predicated_test = model.predict(X_test)
    
        print ("Train score:", model.score(X_train, y_train)*100)
        print ("Test score:", model.score(X_test, y_test)*100)
        print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
        print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
        print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
        # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
        print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
        print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
        print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
        print ()

In [78]:
gaussian_method(x_yeast, y_yeast)

Train score: 54.095045500505556
Test score: 54.34343434343434
Different outputs train: 454 from total of 989
Different outputs test: 226 from total of 495
Accuracy train: 54.095045500505556
F1-score train: 54.095045500505556
Accuracy test: 54.34343434343434
F1-score test: 54.34343434343434

Train score: 54.60060667340748
Test score: 50.101010101010104
Different outputs train: 449 from total of 989
Different outputs test: 247 from total of 495
Accuracy train: 54.60060667340748
F1-score train: 54.60060667340748
Accuracy test: 50.101010101010104
F1-score test: 50.101010101010104

Train score: 54.70171890798786
Test score: 53.73737373737374
Different outputs train: 448 from total of 989
Different outputs test: 229 from total of 495
Accuracy train: 54.70171890798786
F1-score train: 54.70171890798786
Accuracy test: 53.73737373737374
F1-score test: 53.73737373737374

Train score: 52.07280080889788
Test score: 54.141414141414145
Different outputs train: 474 from total of 989
Different outputs 

In [79]:
gaussian_method(x_wine, y_wine)

Train score: 97.37335834896811
Test score: 55.34709193245778
Different outputs train: 28 from total of 1066
Different outputs test: 238 from total of 533
Accuracy train: 97.37335834896811
F1-score train: 97.37335834896811
Accuracy test: 55.34709193245778
F1-score test: 55.34709193245778

Train score: 97.37335834896811
Test score: 56.28517823639775
Different outputs train: 28 from total of 1066
Different outputs test: 233 from total of 533
Accuracy train: 97.37335834896811
F1-score train: 97.37335834896811
Accuracy test: 56.28517823639775
F1-score test: 56.28517823639775

Train score: 97.18574108818011
Test score: 54.78424015009381
Different outputs train: 30 from total of 1066
Different outputs test: 241 from total of 533
Accuracy train: 97.18574108818011
F1-score train: 97.18574108818011
Accuracy test: 54.78424015009381
F1-score test: 54.78424015009381

Train score: 97.37335834896811
Test score: 58.348968105065666
Different outputs train: 28 from total of 1066
Different outputs test: 

In [80]:
gaussian_method(x_mammographic, y_mammographic)

Train score: 90.9375
Test score: 81.61993769470405
Different outputs train: 58 from total of 640
Different outputs test: 59 from total of 321
Accuracy train: 90.9375
F1-score train: 90.9375
Accuracy test: 81.61993769470405
F1-score test: 81.61993769470405

Train score: 90.78125
Test score: 79.75077881619937
Different outputs train: 59 from total of 640
Different outputs test: 65 from total of 321
Accuracy train: 90.78125
F1-score train: 90.78125
Accuracy test: 79.75077881619937
F1-score test: 79.75077881619937

Train score: 91.09375
Test score: 82.55451713395638
Different outputs train: 57 from total of 640
Different outputs test: 56 from total of 321
Accuracy train: 91.09375
F1-score train: 91.09375
Accuracy test: 82.55451713395638
F1-score test: 82.55451713395638

Train score: 91.40625
Test score: 79.75077881619937
Different outputs train: 55 from total of 640
Different outputs test: 65 from total of 321
Accuracy train: 91.40625
F1-score train: 91.40625
Accuracy test: 79.750778816199

# <font color=magenta> 5. GaussianNB

In [81]:
from sklearn.naive_bayes import GaussianNB

In [82]:
def gaussian_nb_method(X, y) -> None:
    
     for i in range(5):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
        model = GaussianNB()
        model.fit(X_train, y_train)
      
        y_predicated_train = model.predict(X_train)
        y_predicated_test = model.predict(X_test)
    
        print ("Iteration: ", i)
        print ("Train score:", model.score(X_train, y_train)*100)
        print ("Test score:", model.score(X_test, y_test)*100)
        print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
        print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
        print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
        # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
        print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
        print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
        print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
        print ()

In [83]:
gaussian_nb_method(x_yeast, y_yeast)

Iteration:  0
Train score: 15.975733063700709
Test score: 14.949494949494948
Different outputs train: 831 from total of 989
Different outputs test: 421 from total of 495
Accuracy train: 15.975733063700709
F1-score train: 15.975733063700709
Accuracy test: 14.949494949494948
F1-score test: 14.949494949494948

Iteration:  1
Train score: 15.470171890798786
Test score: 15.151515151515152
Different outputs train: 836 from total of 989
Different outputs test: 420 from total of 495
Accuracy train: 15.470171890798786
F1-score train: 15.470171890798786
Accuracy test: 15.151515151515152
F1-score test: 15.151515151515152

Iteration:  2
Train score: 16.380182002022245
Test score: 13.737373737373737
Different outputs train: 827 from total of 989
Different outputs test: 427 from total of 495
Accuracy train: 16.380182002022245
F1-score train: 16.380182002022245
Accuracy test: 13.737373737373737
F1-score test: 13.737373737373737

Iteration:  3
Train score: 14.560161779575328
Test score: 16.969696969696

In [84]:
gaussian_nb_method(x_wine, y_wine)

Iteration:  0
Train score: 54.409005628517825
Test score: 55.34709193245778
Different outputs train: 486 from total of 1066
Different outputs test: 238 from total of 533
Accuracy train: 54.409005628517825
F1-score train: 54.409005628517825
Accuracy test: 55.34709193245778
F1-score test: 55.34709193245778

Iteration:  1
Train score: 56.09756097560976
Test score: 54.409005628517825
Different outputs train: 468 from total of 1066
Different outputs test: 243 from total of 533
Accuracy train: 56.09756097560976
F1-score train: 56.09756097560976
Accuracy test: 54.409005628517825
F1-score test: 54.409005628517825

Iteration:  2
Train score: 57.3170731707317
Test score: 54.22138836772983
Different outputs train: 455 from total of 1066
Different outputs test: 244 from total of 533
Accuracy train: 57.3170731707317
F1-score train: 57.3170731707317
Accuracy test: 54.22138836772983
F1-score test: 54.22138836772983

Iteration:  3
Train score: 55.72232645403376
Test score: 56.28517823639775
Different 

In [86]:
gaussian_nb_method(x_mammographic, y_mammographic)

Iteration:  0
Train score: 81.71875
Test score: 79.12772585669782
Different outputs train: 117 from total of 640
Different outputs test: 67 from total of 321
Accuracy train: 81.71875
F1-score train: 81.71874999999999
Accuracy test: 79.12772585669782
F1-score test: 79.12772585669782

Iteration:  1
Train score: 81.25
Test score: 79.12772585669782
Different outputs train: 120 from total of 640
Different outputs test: 67 from total of 321
Accuracy train: 81.25
F1-score train: 81.25
Accuracy test: 79.12772585669782
F1-score test: 79.12772585669782

Iteration:  2
Train score: 79.0625
Test score: 82.55451713395638
Different outputs train: 134 from total of 640
Different outputs test: 56 from total of 321
Accuracy train: 79.0625
F1-score train: 79.0625
Accuracy test: 82.55451713395638
F1-score test: 82.55451713395638

Iteration:  3
Train score: 80.46875
Test score: 78.19314641744548
Different outputs train: 125 from total of 640
Different outputs test: 70 from total of 321
Accuracy train: 80.4

# <font color= magenta> 6. DecisionTreeClassifier

In [87]:
from sklearn.tree import DecisionTreeClassifier

In [91]:
def decision_tree_method(X, y) -> None:
    
     for i in range(5):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
        model = DecisionTreeClassifier(max_depth=5, min_samples_leaf=15)
        model.fit(X_train, y_train)
       
        y_predicated_train = model.predict(X_train)
        y_predicated_test = model.predict(X_test)
    
        print ("Iteration: ", i)
        print ("Train score:", model.score(X_train, y_train)*100)
        print ("Test score:", model.score(X_test, y_test)*100)
        print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
        print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
        print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
        # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
        print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
        print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
        print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
        print ()

In [92]:
decision_tree_method(x_yeast, y_yeast)
#aici avem sigur overfit

Iteration:  0
Train score: 61.375126390293225
Test score: 59.1919191919192
Different outputs train: 382 from total of 989
Different outputs test: 202 from total of 495
Accuracy train: 61.375126390293225
F1-score train: 61.375126390293225
Accuracy test: 59.1919191919192
F1-score test: 59.1919191919192

Iteration:  1
Train score: 62.7906976744186
Test score: 56.16161616161616
Different outputs train: 368 from total of 989
Different outputs test: 217 from total of 495
Accuracy train: 62.7906976744186
F1-score train: 62.7906976744186
Accuracy test: 56.16161616161616
F1-score test: 56.16161616161616

Iteration:  2
Train score: 61.375126390293225
Test score: 56.16161616161616
Different outputs train: 382 from total of 989
Different outputs test: 217 from total of 495
Accuracy train: 61.375126390293225
F1-score train: 61.375126390293225
Accuracy test: 56.16161616161616
F1-score test: 56.16161616161616

Iteration:  3
Train score: 61.57735085945399
Test score: 60.0
Different outputs train: 380 

In [93]:
decision_tree_method(x_wine, y_wine)

Iteration:  0
Train score: 64.82176360225141
Test score: 59.28705440900563
Different outputs train: 375 from total of 1066
Different outputs test: 217 from total of 533
Accuracy train: 64.82176360225141
F1-score train: 64.82176360225141
Accuracy test: 59.28705440900563
F1-score test: 59.28705440900563

Iteration:  1
Train score: 65.66604127579737
Test score: 59.66228893058161
Different outputs train: 366 from total of 1066
Different outputs test: 215 from total of 533
Accuracy train: 65.66604127579737
F1-score train: 65.66604127579737
Accuracy test: 59.66228893058161
F1-score test: 59.66228893058161

Iteration:  2
Train score: 66.88555347091932
Test score: 56.28517823639775
Different outputs train: 353 from total of 1066
Different outputs test: 233 from total of 533
Accuracy train: 66.88555347091932
F1-score train: 66.88555347091932
Accuracy test: 56.28517823639775
F1-score test: 56.28517823639775

Iteration:  3
Train score: 64.25891181988743
Test score: 58.348968105065666
Different ou

In [95]:
decision_tree_method(x_mammographic, y_mammographic)

Iteration:  0
Train score: 84.84375
Test score: 81.93146417445483
Different outputs train: 97 from total of 640
Different outputs test: 58 from total of 321
Accuracy train: 84.84375
F1-score train: 84.84375
Accuracy test: 81.93146417445483
F1-score test: 81.93146417445482

Iteration:  1
Train score: 83.4375
Test score: 84.42367601246106
Different outputs train: 106 from total of 640
Different outputs test: 50 from total of 321
Accuracy train: 83.4375
F1-score train: 83.4375
Accuracy test: 84.42367601246106
F1-score test: 84.42367601246106

Iteration:  2
Train score: 83.28125
Test score: 85.98130841121495
Different outputs train: 107 from total of 640
Different outputs test: 45 from total of 321
Accuracy train: 83.28125
F1-score train: 83.28125
Accuracy test: 85.98130841121495
F1-score test: 85.98130841121495

Iteration:  3
Train score: 83.90625
Test score: 84.73520249221184
Different outputs train: 103 from total of 640
Different outputs test: 49 from total of 321
Accuracy train: 83.90

# <font color= magenta> 7. RandomForestClassifier

In [99]:
from sklearn.ensemble import RandomForestClassifier

In [100]:
def random_forest_method(X, y, max_depth, min_samples_leaf) -> None:
    
    for i in range(5):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
        model = RandomForestClassifier(max_depth=max_depth, min_samples_leaf=min_samples_leaf)
        model.fit(X_train, y_train)
       
        y_predicated_train = model.predict(X_train)
        y_predicated_test = model.predict(X_test)
    
        print ("Train score:", model.score(X_train, y_train)*100)
        print ("Test score:", model.score(X_test, y_test)*100)
        print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
        print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
        print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
        # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
        print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
        print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
        print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)

In [101]:
random_forest_method(x_yeast, y_yeast, 4, 6)

Train score: 62.89180990899899
Test score: 60.2020202020202
Different outputs train: 367 from total of 989
Different outputs test: 197 from total of 495
Accuracy train: 62.89180990899899
F1-score train: 62.89180990899899
Accuracy test: 60.2020202020202
F1-score test: 60.2020202020202
Train score: 64.20626895854399
Test score: 57.17171717171718
Different outputs train: 354 from total of 989
Different outputs test: 212 from total of 495
Accuracy train: 64.20626895854399
F1-score train: 64.20626895854399
Accuracy test: 57.17171717171718
F1-score test: 57.17171717171718
Train score: 61.375126390293225
Test score: 57.77777777777777
Different outputs train: 382 from total of 989
Different outputs test: 209 from total of 495
Accuracy train: 61.375126390293225
F1-score train: 61.375126390293225
Accuracy test: 57.77777777777777
F1-score test: 57.77777777777777
Train score: 62.38624873609707
Test score: 59.3939393939394
Different outputs train: 372 from total of 989
Different outputs test: 201 f

In [102]:
random_forest_method(x_wine, y_wine, 3, 6)

Train score: 62.28893058161351
Test score: 64.72795497185741
Different outputs train: 402 from total of 1066
Different outputs test: 188 from total of 533
Accuracy train: 62.28893058161351
F1-score train: 62.28893058161351
Accuracy test: 64.72795497185741
F1-score test: 64.72795497185741
Train score: 61.350844277673545
Test score: 59.66228893058161
Different outputs train: 412 from total of 1066
Different outputs test: 215 from total of 533
Accuracy train: 61.350844277673545
F1-score train: 61.350844277673545
Accuracy test: 59.66228893058161
F1-score test: 59.66228893058161
Train score: 63.789868667917446
Test score: 55.1594746716698
Different outputs train: 386 from total of 1066
Different outputs test: 239 from total of 533
Accuracy train: 63.789868667917446
F1-score train: 63.789868667917446
Accuracy test: 55.1594746716698
F1-score test: 55.1594746716698
Train score: 59.943714821763606
Test score: 59.28705440900563
Different outputs train: 427 from total of 1066
Different outputs te

In [103]:
random_forest_method(x_mammographic, y_mammographic, 5, 15)

Train score: 83.75
Test score: 82.2429906542056
Different outputs train: 104 from total of 640
Different outputs test: 57 from total of 321
Accuracy train: 83.75
F1-score train: 83.75
Accuracy test: 82.2429906542056
F1-score test: 82.2429906542056
Train score: 82.96875
Test score: 83.48909657320873
Different outputs train: 109 from total of 640
Different outputs test: 53 from total of 321
Accuracy train: 82.96875
F1-score train: 82.96875
Accuracy test: 83.48909657320873
F1-score test: 83.48909657320873
Train score: 82.65625
Test score: 85.35825545171339
Different outputs train: 111 from total of 640
Different outputs test: 47 from total of 321
Accuracy train: 82.65625
F1-score train: 82.65625
Accuracy test: 85.35825545171339
F1-score test: 85.35825545171339
Train score: 82.96875
Test score: 85.35825545171339
Different outputs train: 109 from total of 640
Different outputs test: 47 from total of 321
Accuracy train: 82.96875
F1-score train: 82.96875
Accuracy test: 85.35825545171339
F1-sc

Yeast 55
<br>Wine Red ?
<br>Breast Cancer 75
<br>Primary tumor 48

<font color=blue>Ex3:</font> Documentati in jupyter notebook fiecare din modelele folosite, in limba romana. Daca acelasi algoritm e folosit pentru mai multe seturi de date, puteti face o sectiune separata cu documentarea algoritmilor + trimitere la algoritm. 

# GaussianNB
<br>
<br>
<br>Acest tip de clasificare este foarte simplu, de aceea pentru seturile noastre de date obtinem un rezultat bun pentru setul de date breast_cancer, intrucat acesta se imparte in doua clase(no-recurrence-events si recurrence-events).
<br>Pentru celelalte seturi de date rezultatul este evident, intrucat celelalte seturi de date au in jur de 10 clase.


#  Decision Tree Classifier
<br>
<br>
<br>Aceasta metoda poate clasifica atat doua clase cat si mai multe clase intr-un dataset.
<br>
<br>Parametri:
<br>splitter-> reprezinta strategia aleasa pentru divizarea nodurilor
<br>max_depth-> reprezinta adancimea arborelui
<br>min_samples_split-> nr minim de sample-uri necesare 
<br>min_samples_leaf-> nr minim de sample-uri necesare ca un nod sa fie frunza

# Random Forest Classifier
<br>
<br>
<br>Aceasta metoda foloseste o padure de arbori de decizie random.
<br>Are ca scop controlul fenomenului de overfitting.
<br>
<br>Parametri:
<br>n_estimators-> nr de arbori din padure
<br>max_depth-> adancimea arborelui 
<br>min_samples_split-> nr de sample-uri necesare unui nod pentru a se face split
<br>min_samples_leaf-> nr minim de sample-uri necesare ca un nod sa fie frunza
<br>si altele

<br>
<br>
<br>Observatii:
<br>n_estimators-> nu produce overfitting daca crestem nr de arbori 
<br>max_features-> cu cat e mai mic cu atat evitam overfitting-ul, dar daca e prea mic reteaua face undefitting
<br>max_depth-> are un rol important, reduce complexitatea

# Multi-layer Perceptron classifier
<br>
<br>
<br>Acest model optimizează funcția log-loss folosind LBFGS sau descendență de gradient stocastic.
<br>Această implementare funcționează cu date reprezentate ca tablouri numpy dense sau tablouri scipy slabe de valori în virgulă mobilă.
<br>
<br>Parametri:
<br>hidden_layer_sizes ->  numărul de neuroni din stratul ascuns
<br>activation -> funcție de activare
<br>solver ->  pentru optimizarea ponderilor
<br>alpha -> parametrul de penalizare L2
<br>batch_size -> dimensiunea minibatches-urilor pentru optimizarea stocastica
<br>learning_rate -> rata de învățare pentru actualizări de ponderi
<br>learning_rate_init -> rata inițială de învățare
<br>power_t -> exponent pentru scalare inversă a ratei de învățare 
<br>max_iter -> numărul maxim de iterații
<br>shuffle -> amestecare de sample-uri la fiecare iterație
<br>random_state -> generatorul de numere aleatorii
<br>tol -> toleranță pentru optimizare
<br>verbose -> printare mesaje de progres în stdout
<br>warm_start -> reutilizați soluția apelului anterior
<br>momentum -> momentum pentru actualizarea descendenței gradientului
<br>nesterovs_momentum -> momentumul lui Nesterov
<br>early_stopping -> va anula automat 10% din datele de instruire și va încheia antrenarea atunci când scorul de validare nu se îmbunătățește 
<br>validation_fraction -> proportia datelor de antrenare care vor fi rezervate ca set de validare
<br>beta_1 -> rata de descompunere exponențială pentru estimările vectorului din primul moment
<br>beta_2 -> rata de descompunere exponențială pentru estimările vectorului din al doilea moment
<br>epsilon -> valoare pentru stabilitatea numerică
<br>n_iter_no_change -> numărul maxim de epoci pentru a nu respecta îmbunătățirea dată de tol
<br>max_fun -> numărul maxim de apeluri ale funcției de loss

# GaussianProcessClassifier
<br>
<br>
<br>Este bazată pe aproximarea Laplace.
<br>
<br>Parametri:
<br>kernel -> nucleul care specifică funcția de covarianță 
<br>optimizer -> optimizator intern acceptat pentru optimizarea parametrilor nucleului
<br>n_restarts_optimizer -> numărul de reporniri ale optimizatorului pentru găsirea parametrilor kernel-ului
<br>max_iter_predict -> numărul maxim de iterații din metoda lui Newton
<br>warm_start -> soluția ultimei iterații Newton este utilizată ca inițializare pentru următorul apel
<br>copy_X_train -> o copie persistentă a datelor de instruire 
<br>random_state -> generatorul de numere aleatorii 
<br>multi_class -> specifică modul în care sunt gestionate problemele de clasificare cu mai multe clase
<br>n_jobs -> numărul de joburi utilizate pentru calcul

# KNeighborsClassifier
<br>
<br>
<br>Clasificatorul care implementează votul celor mai apropiați k vecini.
<br>
<br>Parametri:
<br>n_neighbors -> numărul de vecini care vor fi folosiți
<br>weights -> funcția de ponderi folosită în predicție
<br>algorithm -> algoritmul folosit pentru calcularea vecinilor
<br>leaf_size -> dimensiunea frunzelor pentru BallTree sau KDTree
<br>p -> parametru de putere pentru metrica Minkowski
<br>metric -> distanța utilizată pentru arbore
<br>metric_params -> argumente suplimentare pentru funcția metrică
<br>n_jobs -> numărul de joburi utilizate pentru calcul


# C-Support Vector Classification
<br>
<br>
<br>Implementarea se bazează pe libsvm. 
<br>
<br>Parametri:
<br>C -> parametrul de regularizare
<br>kernel -> nucleul care specifică funcția de covarianță 
<br>degree -> gradul funcției nucleului polinomial 
<br>gamma -> coeficientul de nucleu
<br>coef0 -> termen independent în funcția de nucleu
<br>shrinking -> folosește euristicul micșorat
<br>probability -> estimări de probabilitate
<br>tol -> toleranță pentru optimizare 
<br>cache_size -> specifică dimensiunea memoriei cache a nucleului
<br>class_weight -> setați parametrul C al clasei i la clasa_pondere[i]*C pentru SVC
<br>verbose -> printare mesaje de progres în stdout 
<br>max_iter -> numărul maxim de iterații
<br>decision_function_shape -> returnează funcția de decizie 'ovr' sau 'ovo' în funcție de formă
<br>break_ties -> prezicerea va rupe legăturile în funcție de valorile de încredere ale funcției de decizie
<br>random_state -> generatorul de numere aleatorii 

<font color=blue>Ex4:</font>Pentru fiecare model: efectuati o cautare a hiperparametrilor optimi folosind grid search si random search (cu parametrul cv = 4), folosind 5 fold cross validation. 