<font color = Magenta> _Lixandru Andreea-Bianca 382
 <br>   Pepene Adina-Florentina 382_

# Laborator 6

Versiunea 2020-04-01

## Modele de clasificare

Folositi 4 seturi de date pentru probleme de clasificare, plecand de la repository-urile specificate in Cursul 5; de exemplu, [ics.uci.edu](http://archive.ics.uci.edu/ml/datasets.php?format=mat&task=cla&att=&area=&numAtt=&numIns=&type=mvar&sort=nameUp&view=table). Cel putin doua seturi de date sa fie cu valori lipsa. 


1. (20 puncte) Aplicati o metoda de missing value imputation, unde este cazul; justificati si documentati metoda folosita.
1. (numar de modele * numar de seturi de date \* 1 punct = 20 de puncte) Pentru fiecare set de date aplicati 5 modele de clasificare din scikit learn. Pentru fiecare raportati: acuratete, scorul F1 - a se vedea [sklearn.metrics](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) - folosind 5 fold cross validation. Raportati mediile rezultatelor atat pentru fold-urile de antrenare, cat si pentru cele de testare. Rularile se vor face cu valori fixate ale hiperparametrilor. 
1. (numar modele * 4 puncte = 20 puncte) Documentati in jupyter notebook fiecare din modelele folosite, in limba romana. Daca acelasi algoritm e folosit pentru mai multe seturi de date, puteti face o sectiune separata cu documentarea algoritmilor + trimitere la algoritm. 
1. (numar de modele * numar de seturi de date * 1 punct = 20 de puncte) Raportati performanta fiecarui model, folosind 5 fold cross validation. Pentru fiecare din cele 5 rulari, cautati hiperparametrii optimi folosind 4-fold cross validation. Performanta modelului va fi raportata ca medie a celor  5 rulari. 
    *Observatie:* la fiecare din cele 5 rulari, hiperparametrii optimi pot diferi, din cauza datelor utilizate pentru antrenare/validare.  

Se acorda 20 de puncte din oficiu. 

Exemple de modele de clasificare:
1. [Multi-layer Perceptron classifier](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier)
1. [KNN](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier)
1. [SVM](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC)
1. [Gaussian processes](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html#sklearn.gaussian_process.GaussianProcessClassifier)
1. [RBF](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.RBF.html#sklearn.gaussian_process.kernels.RBF)
1. [Decision tree](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier)
1. [Random forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier)
1. [Gaussian Naive bayes](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB) 

*Predare:* 
1. Fiecare student va depune pe site-ul de elearning fisier Jupyter notebook sau arhiva cu astfel de fisiere; 
1. In fiecare fisier se specifica numele celor doi studenti care au lucra in echipa. 
1. Predarea se face in saptamana 13-17 aprilie 2020
1. Revedeti formele ulterioare ale acestui document pentru precizari despre: continutul rezultatelor raportate, modalitate de notare.

# <font color= Magenta> Rezolvare

<font color=blue>Ex1:</font> Aplicati o metoda de missing value imputation, unde este cazul; justificati si documentati metoda folosita.
<br>
><br>Metode posibile:
<br>1. Eliminarea liniilor care contin valori nan.
<br>2. Eliminarea coloanelor care contin nan.
<br>3. Umplerea valorilor nan cu:
> -> o valoare constanta
><br>-> copierea ultimei valori cunoscute(ffill)
><br>-> umplere 'inapoi'(bfill)
><br>-> o valoare calculata (ex: media)

Citim seturile de date si ne uitam care dintre ele au valori lipsa.

In [1]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
names_yeast = ["mcg", "gvh","alm","mit","erl","pox","vac","nuc","class"]

df_yeast = pd.read_csv('./data/yeast/yeast.data',sep=r" +", engine="python", names=names_yeast)

df_yeast.head()

mcg   gvh   alm   mit  erl  pox   vac   nuc class
ADT1_YEAST  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22   MIT
ADT2_YEAST  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22   MIT
ADT3_YEAST  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22   MIT
AAR2_YEAST  0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22   NUC
AATM_YEAST  0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22   MIT

In [3]:
df_yeast.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1484 entries, ADT1_YEAST to G6PD_YEAST
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   mcg     1484 non-null   float64
 1   gvh     1484 non-null   float64
 2   alm     1484 non-null   float64
 3   mit     1484 non-null   float64
 4   erl     1484 non-null   float64
 5   pox     1484 non-null   float64
 6   vac     1484 non-null   float64
 7   nuc     1484 non-null   float64
 8   class   1484 non-null   object 
dtypes: float64(8), object(1)
memory usage: 115.9+ KB


In [4]:
df_wine = pd.read_csv('./data/wine/winequality-red.csv', sep=';')

df_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [6]:
names_mammographics = ["BI-RADS","Age","Shape","Margin","Density","Severity"]

df_mammographics = pd.read_csv('./data/mammographic/mammographic_masses.data', names=names_mammographics)

df_mammographics.head()

BI-RADS Age Shape Margin Density  Severity
0       5  67     3      5       3         1
1       4  43     1      1       ?         1
2       5  58     4      5       3         1
3       4  28     1      1       3         0
4       5  74     1      5       ?         1

In [7]:
'''Valorile din data frame care lipsesc sunt marcate cu '?'.
Ca sa putem vedea cate valori lipsesc trebuie sa inlocuim
toate valorile '?' cu valoarea nan. '''

df_mammographics = df_mammographics.replace('?', np.nan)
df_mammographics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   BI-RADS   959 non-null    object
 1   Age       956 non-null    object
 2   Shape     930 non-null    object
 3   Margin    913 non-null    object
 4   Density   885 non-null    object
 5   Severity  961 non-null    int64 
dtypes: int64(1), object(5)
memory usage: 45.2+ KB


In [8]:
'''Exista mai multe metode prin care putem umple valorile lipsa 
am ales umplerea valorilor prin copierea ultimei valori cunoscute.'''

df_mammographics = df_mammographics.fillna(method='ffill')

df_mammographics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   BI-RADS   961 non-null    object
 1   Age       961 non-null    object
 2   Shape     961 non-null    object
 3   Margin    961 non-null    object
 4   Density   961 non-null    object
 5   Severity  961 non-null    int64 
dtypes: int64(1), object(5)
memory usage: 45.2+ KB


In [9]:
df_mammographics.head()

BI-RADS Age Shape Margin Density  Severity
0       5  67     3      5       3         1
1       4  43     1      1       3         1
2       5  58     4      5       3         1
3       4  28     1      1       3         0
4       5  74     1      5       3         1

In [10]:
df_mammographics = pd.get_dummies(df_mammographics, columns=["Shape", "Margin"])

df_mammographics.head()

BI-RADS Age Density  Severity  Shape_1  Shape_2  Shape_3  Shape_4  Margin_1  \
0       5  67       3         1        0        0        1        0         0   
1       4  43       3         1        1        0        0        0         1   
2       5  58       3         1        0        0        0        1         0   
3       4  28       3         0        1        0        0        0         1   
4       5  74       3         1        1        0        0        0         0   

   Margin_2  Margin_3  Margin_4  Margin_5  
0         0         0         0         1  
1         0         0         0         0  
2         0         0         0         1  
3         0         0         0         0  
4         0         0         0         1

In [11]:
names_breast_cancer = ["class","age","menopause","tumor-size","inv-nodes","node-caps","deg-malig",
                       "breast","breast-quad","irradiat"]

df_breast_cancer = pd.read_csv('./data/breast_cancer/breast-cancer.data', names=names_breast_cancer)

df_breast_cancer.head()

class    age menopause tumor-size inv-nodes node-caps  \
0  no-recurrence-events  30-39   premeno      30-34       0-2        no   
1  no-recurrence-events  40-49   premeno      20-24       0-2        no   
2  no-recurrence-events  40-49   premeno      20-24       0-2        no   
3  no-recurrence-events  60-69      ge40      15-19       0-2        no   
4  no-recurrence-events  40-49   premeno        0-4       0-2        no   

   deg-malig breast breast-quad irradiat  
0          3   left    left_low       no  
1          2  right    right_up       no  
2          2   left    left_low       no  
3          2  right     left_up       no  
4          2  right   right_low       no

In [12]:
'''In data set-ul breast_cancer missing values sunt marcate prin '?',
nu prin valori NaN, asa ca dorim sa inlocuim  valorile '?' cu valori
NaN astfel incat sa putem vedea cre sunt valorile necompletate si
sa le putem inlocui sau sterge.'''

df_breast_cancer = df_breast_cancer.replace('?', np.nan)
df_breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   class        286 non-null    object
 1   age          286 non-null    object
 2   menopause    286 non-null    object
 3   tumor-size   286 non-null    object
 4   inv-nodes    286 non-null    object
 5   node-caps    278 non-null    object
 6   deg-malig    286 non-null    int64 
 7   breast       286 non-null    object
 8   breast-quad  285 non-null    object
 9   irradiat     286 non-null    object
dtypes: int64(1), object(9)
memory usage: 22.5+ KB


In [13]:
names_primary_tumor =["class","age","sex","histologic-type","degree-of-diffe","bone","bone-marrow","lung",
                     "pleura","peritoneum","liver","brain","skin","neck","supraclavicular","axillar","mediastinum","abdomnial"]

df_primary_tumor = pd.read_csv("./data/primary_tumor/primary-tumor.data", names=names_primary_tumor)

df_primary_tumor.head()

class  age sex histologic-type degree-of-diffe  bone  bone-marrow  lung  \
0      1    1   1               ?               3     2            2     1   
1      1    1   1               ?               3     2            2     2   
2      1    1   2               2               3     1            2     2   
3      1    1   2               ?               3     1            2     1   
4      1    1   2               ?               3     1            2     1   

   pleura  peritoneum  liver  brain skin  neck  supraclavicular axillar  \
0       2           2      2      2    2     2                2       2   
1       2           2      1      2    2     2                1       2   
2       2           2      2      2    2     2                2       2   
3       1           2      2      2    2     2                2       2   
4       1           2      2      2    2     2                2       2   

   mediastinum  abdomnial  
0            2          2  
1            1          2  
2            1          2  
3            1          2  
4            1          2

In [14]:
df_primary_tumor = df_primary_tumor.replace('?', np.nan)

df_primary_tumor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   class            339 non-null    int64 
 1   age              339 non-null    int64 
 2   sex              338 non-null    object
 3   histologic-type  272 non-null    object
 4   degree-of-diffe  184 non-null    object
 5   bone             339 non-null    int64 
 6   bone-marrow      339 non-null    int64 
 7   lung             339 non-null    int64 
 8   pleura           339 non-null    int64 
 9   peritoneum       339 non-null    int64 
 10  liver            339 non-null    int64 
 11  brain            339 non-null    int64 
 12  skin             338 non-null    object
 13  neck             339 non-null    int64 
 14  supraclavicular  339 non-null    int64 
 15  axillar          338 non-null    object
 16  mediastinum      339 non-null    int64 
 17  abdomnial        339 non-null    in

In [15]:
'''Pentru dataset-ul breast_cancer am ales sa umplem valorile nan
prin copierea ultimei valori cunoscute, intrucat am dori sa pastram
cat mai multe din liniile si coloanele data set-ului nostru.
Pe coloanele care lipsesc valori nu exista o varietate mare de valori,
deci putem folosi ultima valoare cunoscuta. Setul de date este aproape
complet si nu necesita multe adaugari.'''

df_breast_cancer = df_breast_cancer.fillna(method='ffill')

df_breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   class        286 non-null    object
 1   age          286 non-null    object
 2   menopause    286 non-null    object
 3   tumor-size   286 non-null    object
 4   inv-nodes    286 non-null    object
 5   node-caps    286 non-null    object
 6   deg-malig    286 non-null    int64 
 7   breast       286 non-null    object
 8   breast-quad  286 non-null    object
 9   irradiat     286 non-null    object
dtypes: int64(1), object(9)
memory usage: 22.5+ KB


In [16]:
df_breast_cancer_2 = pd.get_dummies(df_breast_cancer, columns=["age", "menopause", "tumor-size", "inv-nodes", "deg-malig",
                                                              "breast-quad"])

df_breast_cancer_2.head()

class node-caps breast irradiat  age_20-29  age_30-39  \
0  no-recurrence-events        no   left       no          0          1   
1  no-recurrence-events        no  right       no          0          0   
2  no-recurrence-events        no   left       no          0          0   
3  no-recurrence-events        no  right       no          0          0   
4  no-recurrence-events        no  right       no          0          0   

   age_40-49  age_50-59  age_60-69  age_70-79  ...  inv-nodes_6-8  \
0          0          0          0          0  ...              0   
1          1          0          0          0  ...              0   
2          1          0          0          0  ...              0   
3          0          0          1          0  ...              0   
4          1          0          0          0  ...              0   

   inv-nodes_9-11  deg-malig_1  deg-malig_2  deg-malig_3  breast-quad_central  \
0               0            0            0            1                    0   
1               0            0            1            0                    0   
2               0            0            1            0                    0   
3               0            0            1            0                    0   
4               0            0            1            0                    0   

   breast-quad_left_low  breast-quad_left_up  breast-quad_right_low  \
0                     1                    0                      0   
1                     0                    0                      0   
2                     1                    0                      0   
3                     0                    1                      0   
4                     0                    0                      1   

   breast-quad_right_up  
0                     0  
1                     1  
2                     0  
3                     0  
4                     0  

[5 rows x 39 columns]

In [17]:
'''Pentru dataset-ul primary_tumor am ales sa umplem valorile lipsa
cu media de pe coloana, intrucat am observat ca lipsesc multe valori 
de pe aceeasi coloana, deci nu putem avea o evidenta clara asupra
datelor anterioare. Totusi, nu putem decide inca daca renuntam
la coloana digree-of-diffe. Ramane de vazut...'''

df_primary_tumor = df_primary_tumor.apply(lambda x: pd.to_numeric(x), axis=0)

df_primary_tumor = df_primary_tumor.fillna(round(df_primary_tumor.mean()))

df_primary_tumor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   class            339 non-null    int64  
 1   age              339 non-null    int64  
 2   sex              339 non-null    float64
 3   histologic-type  339 non-null    float64
 4   degree-of-diffe  339 non-null    float64
 5   bone             339 non-null    int64  
 6   bone-marrow      339 non-null    int64  
 7   lung             339 non-null    int64  
 8   pleura           339 non-null    int64  
 9   peritoneum       339 non-null    int64  
 10  liver            339 non-null    int64  
 11  brain            339 non-null    int64  
 12  skin             339 non-null    float64
 13  neck             339 non-null    int64  
 14  supraclavicular  339 non-null    int64  
 15  axillar          339 non-null    float64
 16  mediastinum      339 non-null    int64  
 17  abdomnial       

<font color=blue>Ex2:</font> Pentru fiecare set de date aplicati 5 modele de clasificare din scikit learn. Pentru fiecare raportati: acuratete, scorul F1 - a se vedea sklearn.metrics - folosind 5 fold cross validation. Raportati mediile rezultatelor atat pentru fold-urile de antrenare, cat si pentru cele de testare. Rularile se vor face cu valori fixate ale hiperparametrilor.

Trebuie sa separam datele in date de intrare si date de iesire.

In [18]:
x_yeast = df_yeast[["mcg", "gvh", "alm", "mit", "erl", "pox", "vac","nuc"]].to_numpy()
y_yeast = df_yeast["class"].to_numpy()

print("X_yeast", x_yeast[:20, :])
print("Y_yeast", y_yeast[:20])

X_yeast [[0.58 0.61 0.47 0.13 0.5  0.   0.48 0.22]
 [0.43 0.67 0.48 0.27 0.5  0.   0.53 0.22]
 [0.64 0.62 0.49 0.15 0.5  0.   0.53 0.22]
 [0.58 0.44 0.57 0.13 0.5  0.   0.54 0.22]
 [0.42 0.44 0.48 0.54 0.5  0.   0.48 0.22]
 [0.51 0.4  0.56 0.17 0.5  0.5  0.49 0.22]
 [0.5  0.54 0.48 0.65 0.5  0.   0.53 0.22]
 [0.48 0.45 0.59 0.2  0.5  0.   0.58 0.34]
 [0.55 0.5  0.66 0.36 0.5  0.   0.49 0.22]
 [0.4  0.39 0.6  0.15 0.5  0.   0.58 0.3 ]
 [0.43 0.39 0.54 0.21 0.5  0.   0.53 0.27]
 [0.42 0.37 0.59 0.2  0.5  0.   0.52 0.29]
 [0.4  0.42 0.57 0.35 0.5  0.   0.53 0.25]
 [0.6  0.4  0.52 0.46 0.5  0.   0.53 0.22]
 [0.66 0.55 0.45 0.19 0.5  0.   0.46 0.22]
 [0.46 0.44 0.52 0.11 0.5  0.   0.5  0.22]
 [0.47 0.39 0.5  0.11 0.5  0.   0.49 0.4 ]
 [0.58 0.47 0.54 0.11 0.5  0.   0.51 0.26]
 [0.5  0.34 0.55 0.21 0.5  0.   0.49 0.22]
 [0.61 0.6  0.55 0.21 0.5  0.   0.5  0.25]]
Y_yeast ['MIT' 'MIT' 'MIT' 'NUC' 'MIT' 'CYT' 'MIT' 'NUC' 'MIT' 'CYT' 'NUC' 'NUC'
 'CYT' 'MIT' 'MIT' 'CYT' 'CYT' 'NUC' 'NUC' 'NUC']


In [19]:
x_wine = df_wine [["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", 
                   "free sulfur dioxide", "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]].to_numpy()
y_wine = df_wine["quality"].to_numpy()

print("X_wine", x_wine[:20, :])
print("Y_wine", y_wine[:20])

X_wine [[7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00]
 [7.800e+00 7.600e-01 4.000e-02 2.300e+00 9.200e-02 1.500e+01 5.400e+01
  9.970e-01 3.260e+00 6.500e-01 9.800e+00]
 [1.120e+01 2.800e-01 5.600e-01 1.900e+00 7.500e-02 1.700e+01 6.000e+01
  9.980e-01 3.160e+00 5.800e-01 9.800e+00]
 [7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.400e+00 6.600e-01 0.000e+00 1.800e+00 7.500e-02 1.300e+01 4.000e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00]
 [7.300e+00 6.500e-01 0.000e+00 1.200e+00 6.500e-02 1.500e+01 2.100e+01
  9.946e-01 3.390e+00 4.700e-01 1.000e+01]
 [7.800e+00 5.800e-01 2.000e-02 2.000e+00 7.300e-02 9.000e+00 1.800e+01
 

In [20]:
x_mammographic = df_mammographics[["BI-RADS","Age",
                                   "Shape_1","Shape_2","Shape_3","Shape_4",
                                   "Margin_1","Margin_2","Margin_3","Margin_4","Margin_5",
                                   "Density"]].to_numpy()

y_mammographic = df_mammographics["Severity"].to_numpy()

In [21]:
x_breast_cancer = df_breast_cancer[["age", "menopause", "tumor-size", "inv-nodes", "node-caps", "deg-malig", "breast", 
                                    "breast-quad", "irradiat"]].to_numpy()
y_breast_cancer = df_breast_cancer["class"].to_numpy()

print("X_breast_cancer", x_breast_cancer[:20, :])
print("Y_breast_cancer", y_breast_cancer[:20])

X_breast_cancer [['30-39' 'premeno' '30-34' '0-2' 'no' 3 'left' 'left_low' 'no']
 ['40-49' 'premeno' '20-24' '0-2' 'no' 2 'right' 'right_up' 'no']
 ['40-49' 'premeno' '20-24' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['60-69' 'ge40' '15-19' '0-2' 'no' 2 'right' 'left_up' 'no']
 ['40-49' 'premeno' '0-4' '0-2' 'no' 2 'right' 'right_low' 'no']
 ['60-69' 'ge40' '15-19' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['50-59' 'premeno' '25-29' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['60-69' 'ge40' '20-24' '0-2' 'no' 1 'left' 'left_low' 'no']
 ['40-49' 'premeno' '50-54' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['40-49' 'premeno' '20-24' '0-2' 'no' 2 'right' 'left_up' 'no']
 ['40-49' 'premeno' '0-4' '0-2' 'no' 3 'left' 'central' 'no']
 ['50-59' 'ge40' '25-29' '0-2' 'no' 2 'left' 'left_low' 'no']
 ['60-69' 'lt40' '10-14' '0-2' 'no' 1 'left' 'right_up' 'no']
 ['50-59' 'ge40' '25-29' '0-2' 'no' 3 'left' 'right_up' 'no']
 ['40-49' 'premeno' '30-34' '0-2' 'no' 3 'left' 'left_up' 'no']
 ['60-69' 'lt40' '30-34' '0-2'

In [22]:
x_primary_tumor = df_primary_tumor[["age", "sex", "histologic-type", "degree-of-diffe", "bone", "bone-marrow", "lung",
                     "pleura", "peritoneum", "liver", "brain", "skin", "neck", "supraclavicular", "axillar", 
                    "mediastinum", "abdomnial"]].to_numpy()
y_primary_tumor = df_primary_tumor["class"].to_numpy()

print("X_primary_tumor", x_primary_tumor[:20, :])
print("Y_primary_tumor", y_primary_tumor[:20])

X_primary_tumor [[1. 1. 2. 3. 2. 2. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 2. 3. 2. 2. 2. 2. 2. 1. 2. 2. 2. 1. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [1. 2. 2. 3. 1. 2. 2. 2. 2. 2. 1. 2. 2. 1. 1. 1. 2.]
 [2. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 1. 1. 1. 2. 2. 2.]
 [2. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2. 2. 2. 2.]
 [2. 1. 1. 2. 1. 2. 2. 2. 2. 2. 2. 2. 1. 1. 2. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 1. 2. 2. 2. 2. 2. 1. 2. 1. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 1. 2. 2. 1. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 3. 2. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 1. 2.]
 [2. 1. 1. 2. 2. 2. 2. 1. 2. 1. 2. 2. 2. 2. 2. 2. 2.]
 [2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2. 1. 2.]
 [2. 1. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 1. 1. 2. 1. 2.]
 [2. 1. 2. 3

Separam setul de date in set de antrenare si set de testare.
<br> Cand folosim random state facem un random mai stabil.

# <font color= magenta> A. Algoritmi care nu necesita scalarea datelor

# <font color= magenta> 1. DecisionTreeClassifier

In [23]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_validate

In [24]:
def decision_tree_method(X, y) -> None:
    
    model = DecisionTreeClassifier(max_depth=5, min_samples_leaf=15)
        
    scores = cross_validate(model, X, y, cv=5, scoring='accuracy', return_train_score=True)
    scores_f = cross_validate(model, X, y, cv=5, scoring='f1_weighted', return_train_score=True)
    
    print ('Acuratetea setului de antrenare este:', scores['train_score'], 'si are media:', scores['train_score'].mean())
    print ('Acuratetea setului de testare este:', scores['test_score'], 'si are media:', scores['test_score'].mean())

    print ('F1 pentru setul de antrenare este:', scores_f['train_score'], 'si are media', scores_f['train_score'].mean())
    print ('F1 pentru setul de testare este:', scores_f['test_score'], 'si are media', scores_f['test_score'].mean())
    
#      for i in range(5):
#         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
#         model = DecisionTreeClassifier(max_depth=5, min_samples_leaf=15)
#         model.fit(X_train, y_train)
       
#         y_predicated_train = model.predict(X_train)
#         y_predicated_test = model.predict(X_test)
    
#         print ("Iteration: ", i)
#         print ("Train score:", model.score(X_train, y_train)*100)
#         print ("Test score:", model.score(X_test, y_test)*100)
#         print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
#         print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
#         print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
#         # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
#         print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
#         print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
#         print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
#         print ()

In [25]:
decision_tree_method(x_yeast, y_yeast)

Acuratetea setului de antrenare este: [0.61836563 0.61920809 0.60994103 0.63100253 0.61700337] si are media: 0.6191041274866043
Acuratetea setului de testare este: [0.60606061 0.57239057 0.56228956 0.53872054 0.56756757] si are media: 0.5694057694057694
F1 pentru setul de antrenare este: [0.60269116 0.59670385 0.59136236 0.61577814 0.59557764] si are media 0.6004226305634168
F1 pentru setul de testare este: [0.59267024 0.55168132 0.53780771 0.52466963 0.54820681] si are media 0.5510071424486854


In [26]:
decision_tree_method(x_wine, y_wine)

Acuratetea setului de antrenare este: [0.65050821 0.65050821 0.65129007 0.66692729 0.6671875 ] si are media: 0.6572842552775606
Acuratetea setului de testare este: [0.5125     0.4875     0.565625   0.54375    0.57366771] si are media: 0.5366085423197492
F1 pentru setul de antrenare este: [0.62895952 0.62114804 0.63520597 0.63780948 0.64974681] si are media 0.6345739624252036
F1 pentru setul de testare este: [0.46757743 0.4678346  0.55057509 0.52144317 0.55862606] si are media 0.5132112682481044


In [27]:
decision_tree_method(x_mammographic, y_mammographic)

Acuratetea setului de antrenare este: [0.84765625 0.83875163 0.83224967 0.85695709 0.84915475] si are media: 0.8449538767880365
Acuratetea setului de testare este: [0.8238342  0.84895833 0.86979167 0.796875   0.8125    ] si are media: 0.8303918393782382
F1 pentru setul de antrenare este: [0.84707059 0.83891629 0.83109108 0.85711622 0.84912447] si are media 0.8446637289495176
F1 pentru setul de testare este: [0.82347124 0.84835523 0.8694528  0.79712312 0.80697028] si are media 0.8290745357062399


# <font color= magenta> 2. RandomForestClassifier

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
def random_forest_method(X, y, max_depth, min_samples_leaf) -> None:
    
    model = RandomForestClassifier(max_depth=max_depth, min_samples_leaf=min_samples_leaf)
        
    scores = cross_validate(model, X, y, cv=5, scoring='accuracy', return_train_score=True)
    scores_f = cross_validate(model, X, y, cv=5, scoring='f1_weighted', return_train_score=True)
    
    print ('Acuratetea setului de antrenare este:', scores['train_score'], 'si are media:', scores['train_score'].mean())
    print ('Acuratetea setului de testare este:', scores['test_score'], 'si are media:', scores['test_score'].mean())

    print ('F1 pentru setul de antrenare este:', scores_f['train_score'], 'si are media', scores_f['train_score'].mean())
    print ('F1 pentru setul de testare este:', scores_f['test_score'], 'si are media', scores_f['test_score'].mean())
    
    
#     for i in range(5):
#         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
#         model = RandomForestClassifier(max_depth=max_depth, min_samples_leaf=min_samples_leaf)
#         model.fit(X_train, y_train)
       
#         y_predicated_train = model.predict(X_train)
#         y_predicated_test = model.predict(X_test)
    
#         print ("Train score:", model.score(X_train, y_train)*100)
#         print ("Test score:", model.score(X_test, y_test)*100)
#         print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
#         print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
#         print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
#         # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
#         print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
#         print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
#         print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)

In [30]:
random_forest_method(x_yeast, y_yeast, 4, 6)

Acuratetea setului de antrenare este: [0.61331087 0.62426285 0.61752317 0.64195451 0.62626263] si are media: 0.6246628032643197
Acuratetea setului de testare este: [0.58249158 0.57912458 0.63636364 0.52861953 0.61148649] si are media: 0.5876171626171626
F1 pentru setul de antrenare este: [0.59659008 0.60909327 0.60577034 0.61371842 0.61183528] si are media 0.6074014788773463
F1 pentru setul de testare este: [0.56884106 0.5531812  0.61749958 0.53036119 0.5903004 ] si are media 0.5720366855197321


In [31]:
random_forest_method(x_wine, y_wine, 3, 6)

Acuratetea setului de antrenare este: [0.63096169 0.6247068  0.61532447 0.62236122 0.60703125] si are media: 0.6200770865910867
Acuratetea setului de testare este: [0.528125   0.559375   0.6375     0.578125   0.59561129] si are media: 0.5797472570532914
F1 pentru setul de antrenare este: [0.58121611 0.58132796 0.56732681 0.56370289 0.55510429] si are media 0.5697356124342999
F1 pentru setul de testare este: [0.48168137 0.49364677 0.57010909 0.50572575 0.55037101] si are media 0.5203067970530925


In [32]:
random_forest_method(x_mammographic, y_mammographic, 5, 15)

Acuratetea setului de antrenare este: [0.83463542 0.82574772 0.82574772 0.84785436 0.84655397] si are media: 0.8361078375596012
Acuratetea setului de testare este: [0.80829016 0.828125   0.85416667 0.8125     0.8125    ] si are media: 0.8231163644214163
F1 pentru setul de antrenare este: [0.84264466 0.83463991 0.83244309 0.84280549 0.84898253] si are media 0.8403031379328632
F1 pentru setul de testare este: [0.80820724 0.84391962 0.8439538  0.80754816 0.80892937] si are media 0.8225116374577504


# <font color=magenta> B. Algoritmi care necesita scalarea datelor

Pentru urmatoarele metode de clasificare vom scala datele.

In [72]:
from sklearn.preprocessing import MinMaxScaler

In [84]:
scaler = MinMaxScaler()

scaler.fit(x_wine)

x_wine = scaler.transform(x_wine)

In [87]:
# scaler_mammographic = MinMaxScaler()

# scaler.fit(x_mammographic["BI-RADS","Age"])

# #x_mammographic = scaler.transform(x_mammographic)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

# <font color=magenta> 1. KNeighbourClassifier

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [34]:
def k_neighbours_method(X, y, number_of_neighbors) -> None:
    
    model = KNeighborsClassifier(n_neighbors=number_of_neighbors)
    
    scores = cross_validate(model, X, y, cv=5, scoring='accuracy', return_train_score=True)
    scores_f = cross_validate(model, X, y, cv=5, scoring='f1_weighted', return_train_score=True)
    
    print ('Acuratetea setului de antrenare este:', scores['train_score'], 'si are media:', scores['train_score'].mean())
    print ('Acuratetea setului de testare este:', scores['test_score'], 'si are media:', scores['test_score'].mean())

    print ('F1 pentru setul de antrenare este:', scores_f['train_score'], 'si are media', scores_f['train_score'].mean())
    print ('F1 pentru setul de testare este:', scores_f['test_score'], 'si are media', scores_f['test_score'].mean())

#     for i in range(5):
#         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
    
#         model = KNeighborsClassifier(n_neighbors = number_of_neighbors)
#         model.fit(X_train, y_train)
    
#         y_predicated_train = model.predict(X_train)
#         y_predicated_test = model.predict(X_test)
    
#         print ("Iteration:", i)
#         print ("Train score:", model.score(X_train, y_train)*100)
#         print ("Test score:", model.score(X_test, y_test)*100)
#         print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
#         print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
#         print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
#         # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
#         print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
#         print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
#         print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
#         print ()

In [35]:
k_neighbours_method(x_yeast, y_yeast, 10)

Acuratetea setului de antrenare este: [0.64953665 0.65880371 0.64869419 0.65964617 0.6489899 ] si are media: 0.6531341213312569
Acuratetea setului de testare este: [0.54882155 0.56228956 0.5959596  0.53198653 0.60472973] si are media: 0.5687573937573938
F1 pentru setul de antrenare este: [0.6400713  0.64859767 0.64153687 0.6512153  0.63969849] si are media 0.6442239256194373
F1 pentru setul de testare este: [0.53840288 0.55291814 0.59317743 0.51876893 0.59730318] si are media 0.5601141134298688


In [88]:
k_neighbours_method(x_wine, y_wine, 73)

Acuratetea setului de antrenare este: [0.59265051 0.61141517 0.59265051 0.59655981 0.59921875] si are media: 0.5984989493745113
Acuratetea setului de testare este: [0.534375   0.5375     0.63125    0.59375    0.58934169] si are media: 0.5772433385579937
F1 pentru setul de antrenare este: [0.56963722 0.58200114 0.55534125 0.57052625 0.56642527] si are media 0.5687862257960197
F1 pentru setul de testare este: [0.47535029 0.51309811 0.60209033 0.58095024 0.55004792] si are media 0.5443073765758127


In [37]:
k_neighbours_method(x_mammographic, y_mammographic, 10)

Acuratetea setului de antrenare este: [0.8359375  0.8283485  0.82054616 0.83355007 0.83094928] si are media: 0.8298663036410924
Acuratetea setului de testare este: [0.8134715  0.84375    0.828125   0.80729167 0.76041667] si are media: 0.8106109671848014
F1 pentru setul de antrenare este: [0.83599562 0.82800639 0.82057972 0.83340265 0.83061236] si are media 0.829719346813059
F1 pentru setul de testare este: [0.8130872  0.8439538  0.82788534 0.80752742 0.7558542 ] si are media 0.8096615927463491


# <font color=Magenta> 2. MLPClassifier

In [38]:
from sklearn.neural_network import MLPClassifier

In [39]:
def mlp_method(X, y, activ) -> None:
    #‘sgd’ refers to stochastic gradient descent.
    
    model =  MLPClassifier(activation = activ, random_state=10)
    
    scores = cross_validate(model, X, y, cv=5, scoring='accuracy', return_train_score=True)
    scores_f = cross_validate(model, X, y, cv=5, scoring='f1_weighted', return_train_score=True)
    
    print ('Acuratetea setului de antrenare este:', scores['train_score'], 'si are media:', scores['train_score'].mean())
    print ('Acuratetea setului de testare este:', scores['test_score'], 'si are media:', scores['test_score'].mean())

    print ('F1 pentru setul de antrenare este:', scores_f['train_score'], 'si are media', scores_f['train_score'].mean())
    print ('F1 pentru setul de testare este:', scores_f['test_score'], 'si are media', scores_f['test_score'].mean())
    
#     for i in range(5):
#         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
#         model =  MLPClassifier(activation = activ, random_state = 10)
#         model.fit(X_train, y_train)
    
#         y_predicated_train = model.predict(X_train)
#         y_predicated_test = model.predict(X_test)
    
#         print ("Iteration:", i)
#         print ("Train score:", model.score(X_train, y_train)*100)
#         print ("Test score:", model.score(X_test, y_test)*100)
#         print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
#         print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
#         print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
#         # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
#         print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
#         print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
#         print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
#         print ()

In [40]:
mlp_method (x_yeast, y_yeast, 'tanh')

D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % sel

Acuratetea setului de antrenare este: [0.58972199 0.58972199 0.57877001 0.60404381 0.59848485] si are media: 0.5921485282479385
Acuratetea setului de testare este: [0.58922559 0.57912458 0.58922559 0.54208754 0.58783784] si are media: 0.5775002275002274
F1 pentru setul de antrenare este: [0.57604484 0.57556155 0.56599829 0.59077186 0.58408689] si are media 0.578492686928124
F1 pentru setul de testare este: [0.57101369 0.56406854 0.57653579 0.52974852 0.57529287] si are media 0.5633318808664869


D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [41]:
mlp_method (x_wine, y_wine, 'tanh')

D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % sel

Acuratetea setului de antrenare este: [0.62314308 0.64581704 0.61219703 0.60985145 0.615625  ] si are media: 0.6213267200938233
Acuratetea setului de testare este: [0.540625   0.515625   0.565625   0.565625   0.55799373] si are media: 0.5490987460815047
F1 pentru setul de antrenare este: [0.60021854 0.62591633 0.58974116 0.58360973 0.58480903] si are media 0.5968589578870673
F1 pentru setul de testare este: [0.4809405  0.49839484 0.54145581 0.54977549 0.52037727] si are media 0.5181887832976356


D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [42]:
mlp_method (x_mammographic, y_mammographic, 'tanh')

D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % sel

Acuratetea setului de antrenare este: [0.82552083 0.81274382 0.81924577 0.83224967 0.83094928] si are media: 0.8241418779800608
Acuratetea setului de testare este: [0.78238342 0.83333333 0.81770833 0.77604167 0.81770833] si are media: 0.8054350172711571
F1 pentru setul de antrenare este: [0.82558265 0.81284115 0.81932561 0.832477   0.83118112] si are media 0.8242815058738477
F1 pentru setul de testare este: [0.78267573 0.83318864 0.81745415 0.77633975 0.81697262] si are media 0.8053261771644881


D:\Anaconda\envs\dataScience\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [43]:
# mlp_method(X_train_yeast, y_train_yeast, X_test_yeast, y_test_yeast, 'tanh')

# # Train score: 59.45399393326593 #solver='adam'
# # Test score: 61.41414141414141
# # Different outputs train: 401 from total of 989
# # Different outputs test: 191 from total of 495

# # Train score: 62.588473205257834 #solver='lbfgs'
# # Test score: 61.41414141414141
# # Different outputs train: 370 from total of 989
# # Different outputs test: 191 from total of 495

In [44]:
# mlp_method(X_train_wine, y_train_wine, X_test_wine, y_test_wine, 'tanh')

# # Train score: 62.7579737335835 #solver='adam'
# # Test score: 53.09568480300187
# # Different outputs train: 397 from total of 1066
# # Different outputs test: 250 from total of 533

# # Train score: 65.94746716697935 #solver='lbfgs'
# # Test score: 54.971857410881796
# # Different outputs train: 363 from total of 1066
# # Different outputs test: 240 from total of 533

In [45]:
# mlp_method(X_train_breast_cancer, y_train_breast_cancer, X_test_breast_cancer, y_test_breast_cancer, 'relu')

# # Train score: 78.94736842105263 #solver='adam'
# # Test score: 73.95833333333334
# # Different outputs train: 40 from total of 190
# # Different outputs test: 25 from total of 96

# # Train score: 78.94736842105263 #solver='lbfgs'
# # Test score: 68.75
# # Different outputs train: 40 from total of 190
# # Different outputs test: 30 from total of 96

In [46]:
# mlp_method(X_train_primary_tumor, y_train_primary_tumor, X_test_primary_tumor, y_test_primary_tumor, 'identity')

# # Train score: 56.19469026548673 #solver='adam'
# # Test score: 42.47787610619469
# # Different outputs train: 99 from total of 226
# # Different outputs test: 65 from total of 113

# # Train score: 66.3716814159292 #solver='lbfgs'
# # Test score: 38.93805309734513
# # Different outputs train: 76 from total of 226
# # Different outputs test: 69 from total of 113

# <font color=Magenta> 3. SVC

In [47]:
from sklearn.svm import SVC

In [48]:
def svc_method(X, y) -> None:
    
    model = SVC(class_weight=None, random_state = 10)
    
    scores = cross_validate(model, X, y, cv=5, scoring='accuracy', return_train_score=True)
    scores_f = cross_validate(model, X, y, cv=5, scoring='f1_weighted', return_train_score=True)
    
    print ('Acuratetea setului de antrenare este:', scores['train_score'], 'si are media:', scores['train_score'].mean())
    print ('Acuratetea setului de testare este:', scores['test_score'], 'si are media:', scores['test_score'].mean())

    print ('F1 pentru setul de antrenare este:', scores_f['train_score'], 'si are media', scores_f['train_score'].mean())
    print ('F1 pentru setul de testare este:', scores_f['test_score'], 'si are media', scores_f['test_score'].mean())
    
#     for i in range(5):
#         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
#         model = SVC(class_weight=None, random_state = 10)
#         model.fit(X_train,y_train)
    
#         y_predicated_train = model.predict(X_train)
#         y_predicated_test = model.predict(X_test)
    
#         print ("Iteration:", i)
#         print ("Train score:", model.score(X_train, y_train)*100)
#         print ("Test score:", model.score(X_test, y_test)*100)
#         print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
#         print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
#         print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
#         # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
#         print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
#         print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
#         print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
#         print ()

In [49]:
svc_method (x_yeast, y_yeast)

Acuratetea setului de antrenare este: [0.61078349 0.62173547 0.60320135 0.64026959 0.61784512] si are media: 0.618767001665064
Acuratetea setului de testare este: [0.61616162 0.61616162 0.62289562 0.54882155 0.59121622] si are media: 0.599051324051324
F1 pentru setul de antrenare este: [0.60028884 0.61091196 0.59489801 0.63121115 0.60759518] si are media 0.6089810273490984
F1 pentru setul de testare este: [0.60209739 0.60709779 0.6130061  0.53866087 0.58190772] si are media 0.5885539757319778


In [50]:
svc_method (x_wine, y_wine)

Acuratetea setului de antrenare este: [0.49413604 0.50977326 0.50820954 0.51681001 0.515625  ] si are media: 0.5089107701329163
Acuratetea setului de testare este: [0.56875    0.534375   0.475      0.45625    0.47648903] si are media: 0.5021728056426331
F1 pentru setul de antrenare este: [0.44658447 0.46315407 0.45401245 0.46292213 0.46402868] si are media 0.4581403584304849
F1 pentru setul de testare este: [0.51466981 0.48120523 0.41764233 0.3989265  0.4201086 ] si are media 0.4465104911226513


In [51]:
svc_method (x_mammographic, y_mammographic)

Acuratetea setului de antrenare este: [0.71614583 0.69830949 0.6970091  0.70351105 0.71131339] si are media: 0.7052577752492415
Acuratetea setului de testare este: [0.65284974 0.72395833 0.73958333 0.71875    0.67708333] si are media: 0.7024449481865285
F1 pentru setul de antrenare este: [0.71521169 0.69657612 0.69616113 0.70230304 0.71002274] si are media 0.7040549442212546
F1 pentru setul de testare este: [0.65234206 0.72323993 0.737861   0.71819581 0.67429926] si are media 0.7011876125687839


# <font color = magenta> 4. GaussianProcessClassifier

In [52]:
from sklearn.gaussian_process import GaussianProcessClassifier

In [53]:
def gaussian_method(X, y) -> None:
    
    model = GaussianProcessClassifier(random_state = 10)
    
    scores = cross_validate(model, X, y, cv=5, scoring='accuracy', return_train_score=True)
    scores_f = cross_validate(model, X, y, cv=5, scoring='f1_weighted', return_train_score=True)
    
    print ('Acuratetea setului de antrenare este:', scores['train_score'], 'si are media:', scores['train_score'].mean())
    print ('Acuratetea setului de testare este:', scores['test_score'], 'si are media:', scores['test_score'].mean())

    print ('F1 pentru setul de antrenare este:', scores_f['train_score'], 'si are media', scores_f['train_score'].mean())
    print ('F1 pentru setul de testare este:', scores_f['test_score'], 'si are media', scores_f['test_score'].mean())
    
#     for i in range(5):
#         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
#         model = GaussianProcessClassifier(random_state = 10)
#         model.fit(X_train, y_train)
    
#         y_predicated_train = model.predict(X_train)
#         y_predicated_test = model.predict(X_test)
    
#         print ("Train score:", model.score(X_train, y_train)*100)
#         print ("Test score:", model.score(X_test, y_test)*100)
#         print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
#         print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
#         print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
#         # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
#         print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
#         print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
#         print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
#         print ()

In [54]:
gaussian_method(x_yeast, y_yeast)

Acuratetea setului de antrenare este: [0.54928391 0.54759899 0.53664701 0.56697557 0.55387205] si are media: 0.5508755059723889
Acuratetea setului de testare este: [0.53872054 0.56902357 0.56228956 0.4983165  0.55405405] si are media: 0.5444808444808444
F1 pentru setul de antrenare este: [0.52604099 0.52297166 0.51240678 0.54444678 0.5296878 ] si are media 0.5271108034696936
F1 pentru setul de testare este: [0.50722909 0.54379091 0.53765294 0.4757784  0.52781064] si are media 0.5184523929808442


In [55]:
gaussian_method(x_wine, y_wine)

Acuratetea setului de antrenare este: [0.96716185 0.96637998 0.96325254 0.96559812 0.97109375] si are media: 0.9666972488272088
Acuratetea setului de testare este: [0.475     0.446875  0.45625   0.434375  0.4169279] si are media: 0.44588557993730404
F1 pentru setul de antrenare este: [0.96671901 0.96616915 0.96300821 0.96531017 0.97098934] si are media 0.9664391776802462
F1 pentru setul de testare este: [0.45735767 0.4470916  0.45057482 0.4345787  0.39989279] si are media 0.4378991168328115


In [56]:
gaussian_method(x_mammographic, y_mammographic)

Acuratetea setului de antrenare este: [0.90364583 0.90117035 0.89856957 0.90897269 0.90507152] si are media: 0.9034859937147811
Acuratetea setului de testare este: [0.8238342  0.83333333 0.8125     0.77083333 0.765625  ] si are media: 0.8012251727115718
F1 pentru setul de antrenare este: [0.90373237 0.90122172 0.89862229 0.90897269 0.90511345] si are media 0.9035325035892858
F1 pentru setul de testare este: [0.82347124 0.83351426 0.8125     0.77113225 0.76279478] si are media 0.8006825048465511


# <font color=magenta> 5. GaussianNB

In [57]:
from sklearn.naive_bayes import GaussianNB

In [58]:
def gaussian_nb_method(X, y) -> None:
    
    model = GaussianNB()
    
    scores = cross_validate(model, X, y, cv=5, scoring='accuracy', return_train_score=True)
    scores_f = cross_validate(model, X, y, cv=5, scoring='f1_weighted', return_train_score=True)
    
    print ('Acuratetea setului de antrenare este:', scores['train_score'], 'si are media:', scores['train_score'].mean())
    print ('Acuratetea setului de testare este:', scores['test_score'], 'si are media:', scores['test_score'].mean())

    print ('F1 pentru setul de antrenare este:', scores_f['train_score'], 'si are media', scores_f['train_score'].mean())
    print ('F1 pentru setul de testare este:', scores_f['test_score'], 'si are media', scores_f['test_score'].mean())
    
#      for i in range(5):
#         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=i)
        
#         model = GaussianNB()
#         model.fit(X_train, y_train)
      
#         y_predicated_train = model.predict(X_train)
#         y_predicated_test = model.predict(X_test)
    
#         print ("Iteration: ", i)
#         print ("Train score:", model.score(X_train, y_train)*100)
#         print ("Test score:", model.score(X_test, y_test)*100)
#         print ("Different outputs train:", sum(y_predicated_train != y_train), "from total of", len(y_train))
#         print ("Different outputs test:", sum(y_predicated_test != y_test), "from total of", len(y_test))
#         print ("Accuracy train:", metrics.accuracy_score(y_train, y_predicated_train)*100)
#         # average='micro' Calculate metrics globally by counting the total true positives, false negatives and false positives.
#         print ("F1-score train:", metrics.f1_score(y_train, y_predicated_train, average='micro')*100)
#         print ("Accuracy test:", metrics.accuracy_score(y_test, y_predicated_test)*100)
#         print ("F1-score test:", metrics.f1_score(y_test, y_predicated_test, average='micro')*100)
#         print ()

In [59]:
gaussian_nb_method(x_yeast, y_yeast)

Acuratetea setului de antrenare este: [0.16933446 0.15501264 0.23841618 0.1390059  0.13131313] si are media: 0.16661645945554956
Acuratetea setului de testare este: [0.13804714 0.14478114 0.2020202  0.1043771  0.14864865] si are media: 0.14757484757484757
F1 pentru setul de antrenare este: [0.20685848 0.17505935 0.20255769 0.13787692 0.14763672] si are media 0.17399783456613466
F1 pentru setul de testare este: [0.15451384 0.16579675 0.17967319 0.10006242 0.16623635] si are media 0.15325650959500053


In [60]:
gaussian_nb_method(x_wine, y_wine)

Acuratetea setului de antrenare este: [0.57779515 0.5629398  0.56606724 0.56137608 0.565625  ] si are media: 0.5667606528537921
Acuratetea setului de testare este: [0.5125    0.46875   0.58125   0.49375   0.5862069] si are media: 0.5284913793103448
F1 pentru setul de antrenare este: [0.58295396 0.56202501 0.56398573 0.56140101 0.56702308] si are media 0.5674777562235395
F1 pentru setul de testare este: [0.5143785  0.46755027 0.57605361 0.49545849 0.58298556] si are media 0.527285282479964


In [61]:
gaussian_nb_method(x_mammographic, y_mammographic)

Acuratetea setului de antrenare este: [0.80598958 0.79323797 0.8023407  0.80884265 0.79583875] si are media: 0.8012499322713481
Acuratetea setului de testare este: [0.77720207 0.80729167 0.79166667 0.77083333 0.81770833] si are media: 0.7929404145077721
F1 pentru setul de antrenare este: [0.80623946 0.79351515 0.80260838 0.80904691 0.79607415] si are media 0.8014968122005328
F1 pentru setul de testare este: [0.77687625 0.80679471 0.79193841 0.77113225 0.81787205] si are media 0.7929227334573341


Yeast 55
<br>Wine Red ?
<br>Breast Cancer 75
<br>Primary tumor 48

<font color=blue>Ex3:</font> Documentati in jupyter notebook fiecare din modelele folosite, in limba romana. Daca acelasi algoritm e folosit pentru mai multe seturi de date, puteti face o sectiune separata cu documentarea algoritmilor + trimitere la algoritm. 

# GaussianNB
<br>
<br>
<br>Acest tip de clasificare este foarte simplu, de aceea pentru seturile noastre de date obtinem un rezultat bun pentru setul de date breast_cancer, intrucat acesta se imparte in doua clase(no-recurrence-events si recurrence-events).
<br>Pentru celelalte seturi de date rezultatul este evident, intrucat celelalte seturi de date au in jur de 10 clase.


#  Decision Tree Classifier
<br>
<br>
<br>Aceasta metoda poate clasifica atat doua clase cat si mai multe clase intr-un dataset.
<br>
<br>Parametri:
<br>splitter-> reprezinta strategia aleasa pentru divizarea nodurilor
<br>max_depth-> reprezinta adancimea arborelui
<br>min_samples_split-> nr minim de sample-uri necesare 
<br>min_samples_leaf-> nr minim de sample-uri necesare ca un nod sa fie frunza

# Random Forest Classifier
<br>
<br>
<br>Aceasta metoda foloseste o padure de arbori de decizie random.
<br>Are ca scop controlul fenomenului de overfitting.
<br>
<br>Parametri:
<br>n_estimators-> nr de arbori din padure
<br>max_depth-> adancimea arborelui 
<br>min_samples_split-> nr de sample-uri necesare unui nod pentru a se face split
<br>min_samples_leaf-> nr minim de sample-uri necesare ca un nod sa fie frunza
<br>si altele

<br>
<br>
<br>Observatii:
<br>n_estimators-> nu produce overfitting daca crestem nr de arbori 
<br>max_features-> cu cat e mai mic cu atat evitam overfitting-ul, dar daca e prea mic reteaua face undefitting
<br>max_depth-> are un rol important, reduce complexitatea

# Multi-layer Perceptron classifier
<br>
<br>
<br>Acest model optimizează funcția log-loss folosind LBFGS sau descendență de gradient stocastic.
<br>Această implementare funcționează cu date reprezentate ca tablouri numpy dense sau tablouri scipy slabe de valori în virgulă mobilă.
<br>
<br>Parametri:
<br>hidden_layer_sizes ->  numărul de neuroni din stratul ascuns
<br>activation -> funcție de activare
<br>solver ->  pentru optimizarea ponderilor
<br>alpha -> parametrul de penalizare L2
<br>batch_size -> dimensiunea minibatches-urilor pentru optimizarea stocastica
<br>learning_rate -> rata de învățare pentru actualizări de ponderi
<br>learning_rate_init -> rata inițială de învățare
<br>power_t -> exponent pentru scalare inversă a ratei de învățare 
<br>max_iter -> numărul maxim de iterații
<br>shuffle -> amestecare de sample-uri la fiecare iterație
<br>random_state -> generatorul de numere aleatorii
<br>tol -> toleranță pentru optimizare
<br>verbose -> printare mesaje de progres în stdout
<br>warm_start -> reutilizați soluția apelului anterior
<br>momentum -> momentum pentru actualizarea descendenței gradientului
<br>nesterovs_momentum -> momentumul lui Nesterov
<br>early_stopping -> va anula automat 10% din datele de instruire și va încheia antrenarea atunci când scorul de validare nu se îmbunătățește 
<br>validation_fraction -> proportia datelor de antrenare care vor fi rezervate ca set de validare
<br>beta_1 -> rata de descompunere exponențială pentru estimările vectorului din primul moment
<br>beta_2 -> rata de descompunere exponențială pentru estimările vectorului din al doilea moment
<br>epsilon -> valoare pentru stabilitatea numerică
<br>n_iter_no_change -> numărul maxim de epoci pentru a nu respecta îmbunătățirea dată de tol
<br>max_fun -> numărul maxim de apeluri ale funcției de loss

# GaussianProcessClassifier
<br>
<br>
<br>Este bazată pe aproximarea Laplace.
<br>
<br>Parametri:
<br>kernel -> nucleul care specifică funcția de covarianță 
<br>optimizer -> optimizator intern acceptat pentru optimizarea parametrilor nucleului
<br>n_restarts_optimizer -> numărul de reporniri ale optimizatorului pentru găsirea parametrilor kernel-ului
<br>max_iter_predict -> numărul maxim de iterații din metoda lui Newton
<br>warm_start -> soluția ultimei iterații Newton este utilizată ca inițializare pentru următorul apel
<br>copy_X_train -> o copie persistentă a datelor de instruire 
<br>random_state -> generatorul de numere aleatorii 
<br>multi_class -> specifică modul în care sunt gestionate problemele de clasificare cu mai multe clase
<br>n_jobs -> numărul de joburi utilizate pentru calcul

# KNeighborsClassifier
<br>
<br>
<br>Clasificatorul care implementează votul celor mai apropiați k vecini.
<br>
<br>Parametri:
<br>n_neighbors -> numărul de vecini care vor fi folosiți
<br>weights -> funcția de ponderi folosită în predicție
<br>algorithm -> algoritmul folosit pentru calcularea vecinilor
<br>leaf_size -> dimensiunea frunzelor pentru BallTree sau KDTree
<br>p -> parametru de putere pentru metrica Minkowski
<br>metric -> distanța utilizată pentru arbore
<br>metric_params -> argumente suplimentare pentru funcția metrică
<br>n_jobs -> numărul de joburi utilizate pentru calcul


# C-Support Vector Classification
<br>
<br>
<br>Implementarea se bazează pe libsvm. 
<br>
<br>Parametri:
<br>C -> parametrul de regularizare
<br>kernel -> nucleul care specifică funcția de covarianță 
<br>degree -> gradul funcției nucleului polinomial 
<br>gamma -> coeficientul de nucleu
<br>coef0 -> termen independent în funcția de nucleu
<br>shrinking -> folosește euristicul micșorat
<br>probability -> estimări de probabilitate
<br>tol -> toleranță pentru optimizare 
<br>cache_size -> specifică dimensiunea memoriei cache a nucleului
<br>class_weight -> setați parametrul C al clasei i la clasa_pondere[i]*C pentru SVC
<br>verbose -> printare mesaje de progres în stdout 
<br>max_iter -> numărul maxim de iterații
<br>decision_function_shape -> returnează funcția de decizie 'ovr' sau 'ovo' în funcție de formă
<br>break_ties -> prezicerea va rupe legăturile în funcție de valorile de încredere ale funcției de decizie
<br>random_state -> generatorul de numere aleatorii 

<font color=blue>Ex4:</font>Pentru fiecare model: efectuati o cautare a hiperparametrilor optimi folosind grid search si random search (cu parametrul cv = 4), folosind 5 fold cross validation. 